### ISSUE TITLE
[Windows] Crash on install

### ISSUE THREAD

**Issue by thunfisch987** [johnlindquist/kit#1001]
```
Error: spawn C:\Users\Oliver\AppData\Local\Programs\kit\resources\fallbacks\windows\clipboard_x86_64.exe ENOENT
    at r (C:\Users\Oliver\AppData\Local\Programs\kit\resources\app.asar\main.prod.js:2:543688)
    at n (C:\Users\Oliver\AppData\Local\Programs\kit\resources\app.asar\main.prod.js:2:543859)
    at ChildProcess.e.emit (C:\Users\Oliver\AppData\Local\Programs\kit\resources\app.asar\main.prod.js:2:544000)
    at Process.ChildProcess._handle.onexit (node:internal/child_process:291:12)
```

---

Kit 1.40.62
Electron 22.0.0
win32 10.0.22621
Locale: de

**Comment by thunfisch987** [comment]
closing cause issue already exists

**Comment by johnlindquist** [comment]
@thunfisch987 Try the fix mentioned here:

https://github.com/johnlindquist/kit/issues/984#issuecomment-1379993381

**Comment by thunfisch987** [comment]
Commented in the other issue that that fixed it👍
