### ISSUE TITLE
Unhandled promise rejection when trying to open script kit prompt

### ISSUE THREAD

**Issue by Dyvd4** [johnlindquist/kit#1002]
```
TypeError: Object has been destroyed
    at C:\Users\David\AppData\Local\Programs\kit\resources\app.asar\main.prod.js:2:120073
    at l (C:\Users\David\AppData\Local\Programs\kit\resources\app.asar\main.prod.js:2:100762)
    at Generator.<anonymous> (C:\Users\David\AppData\Local\Programs\kit\resources\app.asar\main.prod.js:2:102100)
    at Generator.next (C:\Users\David\AppData\Local\Programs\kit\resources\app.asar\main.prod.js:2:101125)
    at Ni (C:\Users\David\AppData\Local\Programs\kit\resources\app.asar\main.prod.js:2:106754)
    at a (C:\Users\David\AppData\Local\Programs\kit\resources\app.asar\main.prod.js:2:106958)
    at C:\Users\David\AppData\Local\Programs\kit\resources\app.asar\main.prod.js:2:107019
    at new Promise (<anonymous>)
    at C:\Users\David\AppData\Local\Programs\kit\resources\app.asar\main.prod.js:2:106898
    at C:\Users\David\AppData\Local\Programs\kit\resources\app.asar\main.prod.js:2:120726
```

---

Kit 1.40.62
Electron 22.0.0
win32 10.0.22000
Locale: de

**Comment by johnlindquist** [comment]
@Dyvd4 Does this happen every time you try to open the prompt?

Does quitting and trying again fix it?

**Comment by Dyvd4** [comment]
> @Dyvd4 Does this happen every time you try to open the prompt?
> 
> Does quitting and trying again fix it?

First - yes every time.
Second - I actually feel kinda dumb for not trying to quit and start again (it fixed the issue).

**Comment by johnlindquist** [comment]
Thanks for getting back to me. Do you see anything suspicious in either of these logs that may hint at the original error?

Main.log: %USERPROFILE%\AppData\Roaming\Kit\logs\main.log
Kit.log: %USERPROFILE%.kit\logs\kit.log

**Comment by Dyvd4** [comment]
Hi, I can either forward the logs to you (maybe put it in the comments here?), or I investigate it the following days.

**Comment by johnlindquist** [comment]
@Dyvd4 If you could create a gist of each, then paste the links here, that would be great!

**Comment by Dyvd4** [comment]
> @Dyvd4 If you could create a gist of each, then paste the links here, that would be great!

I created a gist with the logs: https://gist.github.com/Dyvd4/919eb16b6823b6aab9c72f4b74df7ebb
