### ISSUE TITLE
Error during script kit backup

### ISSUE THREAD

**Issue by merlindru** [johnlindquist/kit#1005]
```
Error: spawn C:\Users\merli\AppData\Local\Programs\kit\resources\fallbacks\windows\clipboard_x86_64.exe ENOENT
    at r (C:\Users\merli\AppData\Local\Programs\kit\resources\app.asar\main.prod.js:2:543688)
    at n (C:\Users\merli\AppData\Local\Programs\kit\resources\app.asar\main.prod.js:2:543859)
    at ChildProcess.e.emit (C:\Users\merli\AppData\Local\Programs\kit\resources\app.asar\main.prod.js:2:544000)
    at Process.ChildProcess._handle.onexit (node:internal/child_process:291:12)
```

---

Kit 1.40.62
Electron 22.0.0
win32 10.0.22621
Locale: en-US

**Comment by johnlindquist** [comment]
@merlindru Please try the fix mentioned here:

https://github.com/johnlindquist/kit/issues/984#issuecomment-1379993381

**Comment by merlindru** [comment]
Oddly enough, just running the installer a second time fixed it @johnlindquist 😄

**Comment by johnlindquist** [comment]
I'm starting to think there's an async issue where it's not done creating that dir before it tries to rename it. It's the only thing I can think of that would explain why it works on some computers, but not others.
