### ISSUE TITLE
Error after installing

### ISSUE THREAD

**Issue by KapiteinKattenkwaad** [johnlindquist/kit#1014]
I'm getting this error after installing Scriptkit on an Intel Mac Monteray (12.6)

```
TypeError: Object has been destroyed
    at /private/var/folders/63/vb7s8dkj43g6tphwkl8nylx40000gn/T/AppTranslocation/4C4B13AB-9EFB-4DF9-A1C7-0D70CEB69DCA/d/Kit.app/Contents/Resources/app.asar/main.prod.js:2:120073
    at l (/private/var/folders/63/vb7s8dkj43g6tphwkl8nylx40000gn/T/AppTranslocation/4C4B13AB-9EFB-4DF9-A1C7-0D70CEB69DCA/d/Kit.app/Contents/Resources/app.asar/main.prod.js:2:100762)
    at Generator.<anonymous> (/private/var/folders/63/vb7s8dkj43g6tphwkl8nylx40000gn/T/AppTranslocation/4C4B13AB-9EFB-4DF9-A1C7-0D70CEB69DCA/d/Kit.app/Contents/Resources/app.asar/main.prod.js:2:102100)
    at Generator.next (/private/var/folders/63/vb7s8dkj43g6tphwkl8nylx40000gn/T/AppTranslocation/4C4B13AB-9EFB-4DF9-A1C7-0D70CEB69DCA/d/Kit.app/Contents/Resources/app.asar/main.prod.js:2:101125)
    at Ni (/private/var/folders/63/vb7s8dkj43g6tphwkl8nylx40000gn/T/AppTranslocation/4C4B13AB-9EFB-4DF9-A1C7-0D70CEB69DCA/d/Kit.app/Contents/Resources/app.asar/main.prod.js:2:106754)
    at a (/private/var/folders/63/vb7s8dkj43g6tphwkl8nylx40000gn/T/AppTranslocation/4C4B13AB-9EFB-4DF9-A1C7-0D70CEB69DCA/d/Kit.app/Contents/Resources/app.asar/main.prod.js:2:106958)
    at /private/var/folders/63/vb7s8dkj43g6tphwkl8nylx40000gn/T/AppTranslocation/4C4B13AB-9EFB-4DF9-A1C7-0D70CEB69DCA/d/Kit.app/Contents/Resources/app.asar/main.prod.js:2:107019
    at new Promise (<anonymous>)
    at /private/var/folders/63/vb7s8dkj43g6tphwkl8nylx40000gn/T/AppTranslocation/4C4B13AB-9EFB-4DF9-A1C7-0D70CEB69DCA/d/Kit.app/Contents/Resources/app.asar/main.prod.js:2:106898
    at /private/var/folders/63/vb7s8dkj43g6tphwkl8nylx40000gn/T/AppTranslocation/4C4B13AB-9EFB-4DF9-A1C7-0D70CEB69DCA/d/Kit.app/Contents/Resources/app.asar/main.prod.js:2:120726
```

---

Kit 1.40.62
Electron 22.0.0
darwin 21.6.0
Locale: en-GB

**Comment by johnlindquist** [comment]
@KapiteinKattenkwaad Quitting and re-opening will probably sort it out:

https://github.com/johnlindquist/kit/issues/1002#issuecomment-1387737538

I would appreciate if you can share anything that looks suspicious in your logs:
> 
![CleanShot 2023-01-19 at 15 49 57](https://user-images.githubusercontent.com/36073/213579691-624b1912-2f1a-40f3-bea3-cc8bd739f69c.png)

**Comment by KapiteinKattenkwaad** [comment]
@johnlindquist, thanks for getting back to me.
It is working now after reinstalling.
These logs could be useful:

`[2023-01-20 09:38:01.533] [info] 🎨 Creating tray... { checkDb: true }
[2023-01-20 09:38:01.535] [info] 🎨 Tray icon: busy
[2023-01-20 09:38:01.552] [info] Tray created
[2023-01-20 09:38:01.553] [info] 🧐 Checking /Users/max/.kit {
  cwd: '/Users/max/.kit',
  encoding: 'utf-8',
  env: {
    KIT: '/Users/max/.kit',
    KENV: '/Users/max/.kenv',
    PATH: '/Users/max/.knode/bin:/Users/max/.kit/bin:/Users/max/.kit/override/code:/Users/max/.kenv/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin'
  },
  stdio: 'pipe'
}
[2023-01-20 09:38:03.140] [info] Prompt window created
[2023-01-20 09:38:03.141] [info] 

---------------------------------
[2023-01-20 09:38:03.142] [info] Launching Script Kit  1.40.62
[2023-01-20 09:38:03.143] [info] auto updater detected version: 1.40.62
[2023-01-20 09:38:03.144] [info] PATH: /Users/max/.knode/bin:/Users/max/.kit/bin:/Users/max/.kit/override/code:/Users/max/.kenv/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/bin
[2023-01-20 09:38:03.147] [info] Checking online status...
[2023-01-20 09:38:03.164] [info] 📁 GET_ASSET svg/logo.svg
[2023-01-20 09:38:03.165] [info] 📁 Asset path: /private/var/folders/63/vb7s8dkj43g6tphwkl8nylx40000gn/T/AppTranslocation/4C4B13AB-9EFB-4DF9-A1C7-0D70CEB69DCA/d/Kit.app/Contents/Resources/assets/svg/logo.svg
[2023-01-20 09:38:03.189] [info] 🗼 Status: Online
[2023-01-20 09:38:03.191] [info] Didn't find /Users/max/.kit/.kitignore
[2023-01-20 09:38:06.644] [info] 👀 Status: {"status":"default","message":""}
[2023-01-20 09:38:06.645] [info] 🎨 Tray status: default
[2023-01-20 09:38:06.645] [info] 🎨 Tray icon: default
[2023-01-20 09:38:06.650] [info] Stored version: 0.0.0
[2023-01-20 09:38:06.650] [info] /Users/max/.kit
[2023-01-20 09:38:06.651] [info] kit not found
[2023-01-20 09:38:06.659] [info] 📄 scriptPath changed: __app__/splash-screen
[2023-01-20 09:38:06.661] [info] 🌊 Showing Splash Install Screen
[2023-01-20 09:38:06.662] [info] WebContents Focus
[2023-01-20 09:38:06.861] [info] 🔥 Starting Kit First Install
[2023-01-20 09:38:06.861] [info] node not found
[2023-01-20 09:38:06.862] [info] node not found
[2023-01-20 09:38:06.862] [info] Adding node v16.17.1 darwin x64 ~/.knode
[2023-01-20 09:38:07.802] [info] Focus
[2023-01-20 09:38:07.804] [info] 📁 GET_ASSET icon.png
[2023-01-20 09:38:07.804] [info] 📁 Asset path: /private/var/folders/63/vb7s8dkj43g6tphwkl8nylx40000gn/T/AppTranslocation/4C4B13AB-9EFB-4DF9-A1C7-0D70CEB69DCA/d/Kit.app/Contents/Resources/assets/icon.png
[2023-01-20 09:38:07.812] [info] Prompt window in bounds.
[2023-01-20 09:38:07.814] [info] ↖ Bounds: Prompt splash ui { x: 512, y: 151, width: 768, height: 480 }
[2023-01-20 09:38:07.902] [info] Focus
[2023-01-20 09:38:07.953] [info] Download node.js from https://nodejs.org/dist/v16.17.1/node-v16.17.1-darwin-x64.tar.gz
[2023-01-20 09:38:13.549] [error] Error: EROFS: read-only file system, open '/private/var/folders/63/vb7s8dkj43g6tphwkl8nylx40000gn/T/AppTranslocation/4C4B13AB-9EFB-4DF9-A1C7-0D70CEB69DCA/d/Kit.app/Contents/Resources/assets/node.tar.gz'
[2023-01-20 09:38:13.554] [warn] ENOENT: no such file or directory, chmod '/Users/max/.kit/build/install-node.sh'
[2023-01-20 09:38:13.554] [warn] Error: ENOENT: no such file or directory, chmod '/Users/max/.kit/build/install-node.sh'
[2023-01-20 09:38:13.594] [info] 🪟 window-all-closed
[2023-01-20 09:38:13.727] [info] Load /Users/max/.kenv/tmp/install-error/install-error.html in 2
[2023-01-20 09:38:14.159] [error] Error: ENOENT: no such file or directory, chmod '/Users/max/.kit/build/install-node.sh'
    at /private/var/folders/63/vb7s8dkj43g6tphwkl8nylx40000gn/T/AppTranslocation/4C4B13AB-9EFB-4DF9-A1C7-0D70CEB69DCA/d/Kit.app/Contents/Resources/app.asar/main.prod.js:2:501114
    at l (/private/var/folders/63/vb7s8dkj43g6tphwkl8nylx40000gn/T/AppTranslocation/4C4B13AB-9EFB-4DF9-A1C7-0D70CEB69DCA/d/Kit.app/Contents/Resources/app.asar/main.prod.js:2:478683)
    at Generator.<anonymous> (/private/var/folders/63/vb7s8dkj43g6tphwkl8nylx40000gn/T/AppTranslocation/4C4B13AB-9EFB-4DF9-A1C7-0D70CEB69DCA/d/Kit.app/Contents/Resources/app.asar/main.prod.js:2:480021)
    at Generator.next (/private/var/folders/63/vb7s8dkj43g6tphwkl8nylx40000gn/T/AppTranslocation/4C4B13AB-9EFB-4DF9-A1C7-0D70CEB69DCA/d/Kit.app/Contents/Resources/app.asar/main.prod.js:2:479046)
    at vd (/private/var/folders/63/vb7s8dkj43g6tphwkl8nylx40000gn/T/AppTranslocation/4C4B13AB-9EFB-4DF9-A1C7-0D70CEB69DCA/d/Kit.app/Contents/Resources/app.asar/main.prod.js:2:484675)
    at a (/private/var/folders/63/vb7s8dkj43g6tphwkl8nylx40000gn/T/AppTranslocation/4C4B13AB-9EFB-4DF9-A1C7-0D70CEB69DCA/d/Kit.app/Contents/Resources/app.asar/main.prod.js:2:484879)
[2023-01-20 09:39:17.518] [info] 🏃‍♀️ Run /Users/max/.kit/main/index.js
[2023-01-20 09:39:17.519] [info] Ensure two idle processes
[2023-01-20 09:39:17.519] [info] 👶 Create child Prompt process  []
[2023-01-20 09:39:17.525] [info] 2722: 🟢 start idle Prompt
[2023-01-20 09:39:17.525] [info] 2722: 🏎 /Users/max/.kit/main/index.js 
[2023-01-20 09:39:17.527] [error] TypeError: Object has been destroyed
    at /private/var/folders/63/vb7s8dkj43g6tphwkl8nylx40000gn/T/AppTranslocation/4C4B13AB-9EFB-4DF9-A1C7-0D70CEB69DCA/d/Kit.app/Contents/Resources/app.asar/main.prod.js:2:120073
    at l (/private/var/folders/63/vb7s8dkj43g6tphwkl8nylx40000gn/T/AppTranslocation/4C4B13AB-9EFB-4DF9-A1C7-0D70CEB69DCA/d/Kit.app/Contents/Resources/app.asar/main.prod.js:2:100762)
    at Generator.<anonymous> (/private/var/folders/63/vb7s8dkj43g6tphwkl8nylx40000gn/T/AppTranslocation/4C4B13AB-9EFB-4DF9-A1C7-0D70CEB69DCA/d/Kit.app/Contents/Resources/app.asar/main.prod.js:2:102100)
    at Generator.next (/private/var/folders/63/vb7s8dkj43g6tphwkl8nylx40000gn/T/AppTranslocation/4C4B13AB-9EFB-4DF9-A1C7-0D70CEB69DCA/d/Kit.app/Contents/Resources/app.asar/main.prod.js:2:101125)
    at Ni (/private/var/folders/63/vb7s8dkj43g6tphwkl8nylx40000gn/T/AppTranslocation/4C4B13AB-9EFB-4DF9-A1C7-0D70CEB69DCA/d/Kit.app/Contents/Resources/app.asar/main.prod.js:2:106754)
    at a (/private/var/folders/63/vb7s8dkj43g6tphwkl8nylx40000gn/T/AppTranslocation/4C4B13AB-9EFB-4DF9-A1C7-0D70CEB69DCA/d/Kit.app/Contents/Resources/app.asar/main.prod.js:2:106958)
    at /private/var/folders/63/vb7s8dkj43g6tphwkl8nylx40000gn/T/AppTranslocation/4C4B13AB-9EFB-4DF9-A1C7-0D70CEB69DCA/d/Kit.app/Contents/Resources/app.asar/main.prod.js:2:107019
    at new Promise (<anonymous>)
    at /private/var/folders/63/vb7s8dkj43g6tphwkl8nylx40000gn/T/AppTranslocation/4C4B13AB-9EFB-4DF9-A1C7-0D70CEB69DCA/d/Kit.app/Contents/Resources/app.asar/main.prod.js:2:106898
    at /private/var/folders/63/vb7s8dkj43g6tphwkl8nylx40000gn/T/AppTranslocation/4C4B13AB-9EFB-4DF9-A1C7-0D70CEB69DCA/d/Kit.app/Contents/Resources/app.asar/main.prod.js:2:120726
[2023-01-20 09:39:17.709] [info] Add two idle processes
[2023-01-20 09:39:17.710] [info] 👶 Create child Prompt process  []
[2023-01-20 09:39:17.713] [info] 2723: 🟢 start idle Prompt
[2023-01-20 09:39:17.713] [info] 👶 Create child Prompt process  []
[2023-01-20 09:39:17.716] [info] 2724: 🟢 start idle Prompt
[2023-01-20 09:39:17.717] [info] EXIT { pid: 2722, code: 1 }
[2023-01-20 09:39:17.718] [error] 2722: 🟥 exit 1. Prompt process: /Users/max/.kit/main/index.js
[2023-01-20 09:39:17.718] [error] 👋 Ask for help: https://github.com/johnlindquist/kit/discussions/categories/errors
[2023-01-20 09:39:17.719] [info] 2722: 🛑 removed
[2023-01-20 09:39:17.879] [info] EXIT { pid: 2724, code: 1 }
[2023-01-20 09:39:17.881] [error] 2724: 🟥 exit 1. Prompt process: 
[2023-01-20 09:39:17.881] [error] 👋 Ask for help: https://github.com/johnlindquist/kit/discussions/categories/errors
[2023-01-20 09:39:17.881] [info] 2724: 🛑 removed
[2023-01-20 09:39:17.882] [info] EXIT { pid: 2723, code: 1 }
[2023-01-20 09:39:17.882] [error] 2723: 🟥 exit 1. Prompt process: 
[2023-01-20 09:39:17.883] [error] 👋 Ask for help: https://github.com/johnlindquist/kit/discussions/categories/errors
[2023-01-20 09:39:17.883] [info] 2723: 🛑 removed
[2023-01-20 09:39:45.787] [info] 🎨 Tray status: default
[2023-01-20 09:39:45.788] [info] 🎨 Tray icon: default
[2023-01-20 09:39:45.789] [info] 👀 Status: {"status":"default","message":""}
[2023-01-20 09:51:51.588] [info] 🔒 System locked. Reloading prompt window.
[2023-01-20 09:51:51.589] [warn] Uncaught Exception: Object has been destroyed
[2023-01-20 09:51:51.590] [warn] TypeError: Object has been destroyed
    at BrowserWindow.s.reload (node:electron/js2c/browser_init:2:11004)
    at fo (/private/var/folders/63/vb7s8dkj43g6tphwkl8nylx40000gn/T/AppTranslocation/4C4B13AB-9EFB-4DF9-A1C7-0D70CEB69DCA/d/Kit.app/Contents/Resources/app.asar/main.prod.js:2:123696)
    at PowerMonitor.<anonymous> (/private/var/folders/63/vb7s8dkj43g6tphwkl8nylx40000gn/T/AppTranslocation/4C4B13AB-9EFB-4DF9-A1C7-0D70CEB69DCA/d/Kit.app/Contents/Resources/app.asar/main.prod.js:2:113273)
    at PowerMonitor.emit (node:events:525:35)
[2023-01-20 09:51:51.592] [error] TypeError: Object has been destroyed
    at BrowserWindow.s.reload (node:electron/js2c/browser_init:2:11004)
    at fo (/private/var/folders/63/vb7s8dkj43g6tphwkl8nylx40000gn/T/AppTranslocation/4C4B13AB-9EFB-4DF9-A1C7-0D70CEB69DCA/d/Kit.app/Contents/Resources/app.asar/main.prod.js:2:123696)
    at PowerMonitor.<anonymous> (/private/var/folders/63/vb7s8dkj43g6tphwkl8nylx40000gn/T/AppTranslocation/4C4B13AB-9EFB-4DF9-A1C7-0D70CEB69DCA/d/Kit.app/Contents/Resources/app.asar/main.prod.js:2:113273)
    at PowerMonitor.emit (node:events:525:35)
[2023-01-20 10:05:13.673] [info] { updateLogPath: '/Users/max/Library/Logs/Kit/update.log' }
[2023-01-20 10:05:13.681] [info] { mainLogPath: '/Users/max/Library/Logs/Kit/main.log' }
[2023-01-20 10:05:13.681] [info] 




🟢🟢 🟢  !!!SCRIPT KIT TIME!!! 🟢 🟢 🟢 
[2023-01-20 10:05:14.114] [info] second-instance {
  preventDefault: '[function] function preventDefault() { [native code] }',
  sender: {
    quit: '[function] function quit() { [native code] }',
    exit: '[function] function exit() { [native code] }',
    focus: '[function] function focus() { [native code] }',
    getVersion: '[function] function getVersion() { [native code] }',
    setVersion: '[function] function setVersion() { [native code] }',
    getName: '[function] function getName() { [native code] }',
    setName: '[function] function setName() { [native code] }',
    isReady: '[function] function isReady() { [native code] }',
    whenReady: '[function] function whenReady() { [native code] }',
    addRecentDocument: '[function] function addRecentDocument() { [native code] }',
    clearRecentDocuments: '[function] function clearRecentDocuments() { [native code] }',
    isDefaultProtocolClient: '[function] function isDefaultProtocolClient() { [native code] }',
    setAsDefaultProtocolClient: '[function] function setAsDefaultProtocolClient() { [native code] }',
    removeAsDefaultProtocolClient: '[function] function removeAsDefaultProtocolClient() { [native code] }',
    getApplicationInfoForProtocol: '[function] function getApplicationInfoForProtocol() { [native code] }',
    getApplicationNameForProtocol: '[function] function getApplicationNameForProtocol() { [native code] }',
    setBadgeCount: '[function] function setBadgeCount() { [native code] }',
    getBadgeCount: '[function] function getBadgeCount() { [native code] }',
    getLoginItemSettings: '[function] function getLoginItemSettings() { [native code] }',
    setLoginItemSettings: '[function] function setLoginItemSettings() { [native code] }',
    isEmojiPanelSupported: '[function] function isEmojiPanelSupported() { [native code] }',
    hide: '[function] function hide() { [native code] }',
    isHidden: '[function] function isHidden() { [native code] }',
    show: '[function] function show() { [native code] }',
    setUserActivity: '[function] function setUserActivity() { [native code] }',
    getCurrentActivityType: '[function] function getCurrentActivityType() { [native code] }',
    invalidateCurrentActivity: '[function] function invalidateCurrentActivity() { [native code] }',
    resignCurrentActivity: '[function] function resignCurrentActivity() { [native code] }',
    updateCurrentActivity: '[function] function updateCurrentActivity() { [native code] }',
    moveToApplicationsFolder: '[function] function moveToApplicationsFolder() { [native code] }',
    isInApplicationsFolder: '[function] function isInApplicationsFolder() { [native code] }',
    setActivationPolicy: '[function] function setActivationPolicy() { [native code] }',
    setAboutPanelOptions: '[function] function setAboutPanelOptions() { [native code] }',
    showAboutPanel: '[function] function showAboutPanel() { [native code] }',
    isSecureKeyboardEntryEnabled: '[function] function isSecureKeyboardEntryEnabled() { [native code] }',
    setSecureKeyboardEntryEnabled: '[function] function setSecureKeyboardEntryEnabled() { [native code] }',
    showEmojiPanel: '[function] function showEmojiPanel() { [native code] }',
    isPackaged: true,
    setAppPath: '[function] function setAppPath() { [native code] }',
    getAppPath: '[function] function getAppPath() { [native code] }',
    setPath: '[function] function setPath() { [native code] }',
    getPath: '[function] function getPath() { [native code] }',
    setAppLogsPath: '[function] function setAppLogsPath() { [native code] }',
    setDesktopName: '[function] function setDesktopName() { [native code] }',
    getLocale: '[function] function getLocale() { [native code] }',
    getPreferredSystemLanguages: '[function] function getPreferredSystemLanguages() { [native code] }',
    getSystemLocale: '[function] function getSystemLocale() { [native code] }',
    getLocaleCountryCode: '[function] function getLocaleCountryCode() { [native code] }',
    hasSingleInstanceLock: '[function] function hasSingleInstanceLock() { [native code] }',
    requestSingleInstanceLock: '[function] function requestSingleInstanceLock() { [native code] }',
    releaseSingleInstanceLock: '[function] function releaseSingleInstanceLock() { [native code] }',
    relaunch: '[function] function relaunch() { [native code] }',
    isAccessibilitySupportEnabled: '[function] function isAccessibilitySupportEnabled() { [native code] }',
    setAccessibilitySupportEnabled: '[function] function setAccessibilitySupportEnabled() { [native code] }',
    disableHardwareAcceleration: '[function] function disableHardwareAcceleration() { [native code] }',
    disableDomainBlockingFor3DAPIs: '[function] function disableDomainBlockingFor3DAPIs() { [native code] }',
    getFileIcon: '[function] function getFileIcon() { [native code] }',
    getAppMetrics: '[function] function getAppMetrics() { [native code] }',
    getGPUFeatureStatus: '[function] function getGPUFeatureStatus() { [native code] }',
    getGPUInfo: '[function] function getGPUInfo() { [native code] }',
    dock: {
      bounce: '[function] function () { [native code] }',
      cancelBounce: '[function] function () { [native code] }',
      downloadFinished: '[function] function () { [native code] }',
      setBadge: '[function] function () { [native code] }',
      getBadge: '[function] function () { [native code] }',
      hide: '[function] function () { [native code] }',
      show: '[function] function () { [native code] }',
      isVisible: '[function] function () { [native code] }',
      setMenu: '[function] t=>{c=t,e(t)}',
      setIcon: '[function] function () { [native code] }',
      getMenu: '[function] ()=>c'
    },
    runningUnderRosettaTranslation: false,
    runningUnderARM64Translation: false,
    userAgentFallback: 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Kit/1.40.62 Chrome/108.0.5359.62 Electron/22.0.0 Safari/537.36',
    configureHostResolver: '[function] function configureHostResolver() { [native code] }',
    enableSandbox: '[function] function enableSandbox() { [native code] }',
    commandLine: {
      hasSwitch: '[function] e=>a.hasSwitch(String(e))',
      getSwitchValue: '[function] e=>a.getSwitchValue(String(e))',
      appendSwitch: '[function] (e,t)=>a.appendSwitch(String(e),void 0===t?t:String(t))',
      appendArgument: '[function] e=>a.appendArgument(String(e))',
      removeSwitch: '[function] e=>a.removeSwitch(String(e))'
    },
    setAppUserModelId: '[function] ()=>{}',
    _events: {
      'certificate-error': '[function] (t,r,...o)=>{r.emit(e,t,...o)}',
      'select-client-certificate': '[function] (t,r,...o)=>{r.emit(e,t,...o)}',
      'child-process-gone': '[function] function(...e){0!==this.listenerCount(t)&&(o(),this.emit(t,...e))}',
      'render-process-gone': '[function] function(...e){0!==this.listenerCount(t)&&(o(),this.emit(t,...e))}',
      quit: '[function] (e,t)=>{process.emit("exit",t)}',
      'window-all-closed': [
        '[function] ()=>{1===a.listenerCount("window-all-closed")&&a.quit()}',
        '[function] function(e){Ro.log("🪟 window-all-closed"),e.preventDefault()}'
      ],
      'web-contents-created': [
        `[function] function(t,r){var n=r.executeJavaScript('try {require("'+e+'")} catch(e){}; void 0;');n&&"function"==typeof n.catch&&n.catch((function(){}))}`,
        `[function] function(t,r){var n=r.executeJavaScript('try {require("'+e+'")} catch(e){}; void 0;');n&&"function"==typeof n.catch&&n.catch((function(){}))}`,
        `[function] function(t,r){var n=r.executeJavaScript('try {require("'+e+'")} catch(e){}; void 0;');n&&"function"==typeof n.catch&&n.catch((function(){}))}`,
        `[function] function(t,r){var n=r.executeJavaScript('try {require("'+e+'")} catch(e){}; void 0;');n&&"function"==typeof n.catch&&n.catch((function(){}))}`,
        '[function] function(e,t){t.on("will-navigate",function(){var e=yd(md().mark((function e(t,r){var i;return md().wrap((function(e){for(;;)switch(e.prev=e.next){case 0:if(i=new URL(r),console.log({url:i}),t.preventDefault(),"scriptkit.com"!==i.host||"/api/new"!==i.pathname){e.next=8;break}return e.next=6,Td("new",i.searchParams);case 6:e.next=14;break;case 8:if("kit:"!==i.protocol){e.next=13;break}return e.next=11,Td(i.pathname,i.searchParams);case 11:e.next=14;break;case 13:"submit:"===i.protocol?Xi(T.Channel.SET_SUBMIT_VALUE,i.pathname):i.protocol.startsWith("http")&&n.shell.openExternal(i.href);case 14:case"end":return e.stop()}}),e)})));return function(t,r){return e.apply(this,arguments)}}())}'
      ],
      'second-instance': '[function] function(t,r){return e.apply(this,arguments)}',
      activate: '[function] function(t,r){return e.apply(this,arguments)}'
    },
    _eventsCount: 9
  }
} [
  '/Applications/Kit.app/Contents/MacOS/Kit',
  '--allow-file-access-from-files',
  '--enable-avfoundation'
]`

**Comment by johnlindquist** [comment]
Awesome, thanks, super helpful.

Are you the admin of the machine you're on? Or using VPN?

This line is curious:

```
Error: EROFS: read-only file system, open
```

It's due to something with the node download/extraction process.

**Comment by KapiteinKattenkwaad** [comment]
I am the admin of my machine but not on a VPN.
I do have a proxy open on my machine that's loading up localhost:3000 and pointing it to localhost:3010 for SSL purpose
