### ISSUE TITLE
No sure if anyone else see this issue

### ISSUE THREAD

**Issue by le250055** [johnlindquist/kit#1015]
```
Error: ENOENT: no such file or directory, chmod '/Users/home/.kit/build/install-node.sh'
    at /Applications/Kit.app/Contents/Resources/app.asar/main.prod.js:2:501114
    at l (/Applications/Kit.app/Contents/Resources/app.asar/main.prod.js:2:478683)
    at Generator.<anonymous> (/Applications/Kit.app/Contents/Resources/app.asar/main.prod.js:2:480021)
    at Generator.next (/Applications/Kit.app/Contents/Resources/app.asar/main.prod.js:2:479046)
    at vd (/Applications/Kit.app/Contents/Resources/app.asar/main.prod.js:2:484675)
    at a (/Applications/Kit.app/Contents/Resources/app.asar/main.prod.js:2:484879)
```

---

Kit 1.40.62
Electron 22.0.0
darwin 22.2.0
Locale: en-US

**Comment by johnlindquist** [comment]
@le250055 Yeah, quitting and opening the app again should fix it. It's come up randomly, something to do with how Kit.app is downloading the node tar, but no detecting it in time. I'm still hunting down the core issue.
