### ISSUE TITLE
Error on installing on windows

### ISSUE THREAD

**Issue by davbrito** [johnlindquist/kit#1019]
```
Error: spawn C:\Users\usuario\AppData\Local\Programs\kit\resources\fallbacks\windows\clipboard_x86_64.exe ENOENT
    at r (C:\Users\usuario\AppData\Local\Programs\kit\resources\app.asar\main.prod.js:2:543688)
    at n (C:\Users\usuario\AppData\Local\Programs\kit\resources\app.asar\main.prod.js:2:543859)
    at ChildProcess.e.emit (C:\Users\usuario\AppData\Local\Programs\kit\resources\app.asar\main.prod.js:2:544000)
    at Process.ChildProcess._handle.onexit (node:internal/child_process:291:12)
```

---

Kit 1.40.62
Electron 22.0.0
win32 10.0.22621
Locale: es-419

**Comment by jcgerhard** [comment]
Same issue on:

- Microsoft Windows 10 Home | 10.0.19045 Build 19045
- Microsoft Windows 11 Home | 10.0.22000 Build 22000
- Kit version: Kit-Windows-1.40.62-x64.exe

```
Unhandled Promise Rejection
Error: spawn C:/Users/jang/AppData/Local/Programs/kit/resources/fallbacks/windows/clipboard_x86_64.exe ENOENT
    at r (C:/Users/jang/AppData/Local/Programs/kit/resources/app.asar/main.prod.js:2:543688)
    at n (C:/Users/jang/AppData/Local/Programs/kit/resources/app.asar/main.prod.js:2:543859)
    at ChildProcess.e.emit (C:/Users/jang/AppData/Local/Programs/kit/resources/app.asar/main.prod.js:2:544000)
    at Process.ChildProcess._handle.onexit (node:internal/child_process:291:12)
```

**Comment by thunfisch987** [comment]
Try this fix: https://github.com/johnlindquist/kit/issues/984#issuecomment-1379993381

had the same error and it worked for me

**Comment by DeanMarkTaylor** [comment]
I noted that just initially starting the installer by right clicking and selecting to "Run as Administrator" allowed the installer to complete.
