### ISSUE TITLE
Windows installation error

### ISSUE THREAD

**Issue by artless-soul** [johnlindquist/kit#1022]
```
Error: spawn C:\Users\pat\AppData\Local\Programs\kit\resources\fallbacks\windows\clipboard_x86_64.exe ENOENT
    at r (C:\Users\pat\AppData\Local\Programs\kit\resources\app.asar\main.prod.js:2:543688)
    at n (C:\Users\pat\AppData\Local\Programs\kit\resources\app.asar\main.prod.js:2:543859)
    at ChildProcess.e.emit (C:\Users\pat\AppData\Local\Programs\kit\resources\app.asar\main.prod.js:2:544000)
    at Process.ChildProcess._handle.onexit (node:internal/child_process:291:12)
```

---

Kit 1.40.62
Electron 22.0.0
win32 10.0.19044
Locale: en-US

**Comment by johnlindquist** [comment]
@artless-soul This will most likely fix it for you:

https://github.com/johnlindquist/kit/issues/984#issuecomment-1379993381

**Comment by artless-soul** [comment]
Thanks! That was the fix. :-)
