### ISSUE TITLE
Error: write EOF at WriteWrap.onWriteComplete

### ISSUE THREAD

**Issue by 18jad** [johnlindquist/kit#1026]
```
Error: write EOF
    at WriteWrap.onWriteComplete [as oncomplete] (node:internal/stream_base_commons:94:16)
```

---

Kit 1.40.62
Electron 22.0.0
win32 10.0.22623
Locale: en-GB

I am using nvm to control node version, current activated version is 16.19.0 i also tried the 18.13.0 but same error....

**Comment by 18jad** [comment]
I found this in the logs: 
```
[2023-01-21 18:15:41.347] [info] file:///C:/Users/Jad%20LastName/.kit/core/utils.js:182
    throw new Error(`${script} not found`);
          ^

Error: C:\Users\Jad not found
    at resolveToScriptPath (file:///C:/Users/Jad%20LastName/.kit/core/utils.js:182:11)
    at run (file:///C:/Users/Jad%20LastName/.kit/core/utils.js:446:26)
    at runCli (file:///C:/Users/Jad%20LastName/.kit/cli/kit.js:134:15)
    at async file:///C:/Users/Jad%20LastName/.kit/run/terminal.js:16:1
```
Apparently, if you have a space in your username folder (in my case it is "firstname lastname") it will ignore the rest of it and give path not found...
