### ISSUE TITLE
Linux build testing

### ISSUE THREAD

**Issue by benjaminkitt** [johnlindquist/kit#1027]
Working my way through trying to get this running on Linux with AppImage build. First error had me install xsel. This is what cropped up next. Running Ubuntu.

```
Error: ENOENT: no such file or directory, chmod '/home/benjamin/.kit/build/install-node.sh'
    at /tmp/.mount_Kit-LixkCG1r/resources/app.asar/main.prod.js:2:501114
    at l (/tmp/.mount_Kit-LixkCG1r/resources/app.asar/main.prod.js:2:478683)
    at Generator.<anonymous> (/tmp/.mount_Kit-LixkCG1r/resources/app.asar/main.prod.js:2:480021)
    at Generator.next (/tmp/.mount_Kit-LixkCG1r/resources/app.asar/main.prod.js:2:479046)
    at vd (/tmp/.mount_Kit-LixkCG1r/resources/app.asar/main.prod.js:2:484675)
    at a (/tmp/.mount_Kit-LixkCG1r/resources/app.asar/main.prod.js:2:484879)
```

---

Kit 1.40.62
Electron 22.0.0
linux 5.15.0-58-generic
Locale: en-US

**Comment by johnlindquist** [comment]
Try quitting and opening again. It may have been a false positive during the setup process

**Comment by benjaminkitt** [comment]
Nope, happens on each start, and to be fair `/home/benjamin/.kit/` _doesn't_ exist.

**Comment by johnlindquist** [comment]
@benjaminkitt Ok, thanks. I did a recent refactor to speed up the install process. I must have messed up the Linux logic. I'll try to get it sorted and tested on Mac parallels this week. I'll ping you when I have the new release out. Thank you for your patience.

**Comment by TAKANOME-DEV** [comment]
@benjaminkitt I was able to run it on ubuntu 22.04. Checkout the discussion -> https://github.com/johnlindquist/kit/discussions/121#discussioncomment-4766021
