### ISSUE TITLE
error for install app 

### ISSUE THREAD

**Issue by mojtaba1180** [johnlindquist/kit#1029]
```
Error: spawn C:\Users\moham\AppData\Local\Programs\kit\resources\fallbacks\windows\clipboard_x86_64.exe ENOENT
    at r (C:\Users\moham\AppData\Local\Programs\kit\resources\app.asar\main.prod.js:2:543688)
    at n (C:\Users\moham\AppData\Local\Programs\kit\resources\app.asar\main.prod.js:2:543859)
    at ChildProcess.e.emit (C:\Users\moham\AppData\Local\Programs\kit\resources\app.asar\main.prod.js:2:544000)
    at Process.ChildProcess._handle.onexit (node:internal/child_process:291:12)
```

---

Kit 1.40.62
Electron 22.0.0
win32 10.0.19045
Locale: en-US

**Comment by johnlindquist** [comment]
Please try this fix:

https://github.com/johnlindquist/kit/issues/984

**Comment by mojtaba1180** [comment]
tnx
