### ISSUE TITLE
Error upon starting Kit-Linux-1.40.62-x86_64.AppImage

### ISSUE THREAD

**Issue by mstine** [johnlindquist/kit#1032]
```
➜  Downloads chmod +x Kit-Linux-1.40.62-x86_64.AppImage                                                                                               
➜  Downloads ./Kit-Linux-1.40.62-x86_64.AppImage
```

```
Error: ENOENT: no such file or directory, chmod '/home/mstine/.kit/build/install-node.sh'
    at /tmp/.mount_Kit-LiBQyWIv/resources/app.asar/main.prod.js:2:501114
    at l (/tmp/.mount_Kit-LiBQyWIv/resources/app.asar/main.prod.js:2:478683)
    at Generator.<anonymous> (/tmp/.mount_Kit-LiBQyWIv/resources/app.asar/main.prod.js:2:480021)
    at Generator.next (/tmp/.mount_Kit-LiBQyWIv/resources/app.asar/main.prod.js:2:479046)
    at vd (/tmp/.mount_Kit-LiBQyWIv/resources/app.asar/main.prod.js:2:484675)
    at a (/tmp/.mount_Kit-LiBQyWIv/resources/app.asar/main.prod.js:2:484879)
```

---

Kit 1.40.62
Electron 22.0.0
linux 6.0.12-76060006-generic
Locale: en-US

**Comment by mstine** [comment]
Attaching STDOUT and STDERR.
[STDERR.log](https://github.com/johnlindquist/kit/files/10472818/STDERR.log)
[STDOUT.log](https://github.com/johnlindquist/kit/files/10472819/STDOUT.log)

**Comment by mstine** [comment]
Just realized I duplicated https://github.com/johnlindquist/kit/issues/1027. Leaving it here in case you want additional context.

**Comment by mstine** [comment]
So I do not know much about how the AppImage format works, but from what I can surmise, it is mounting itself to a directory under `/tmp`. In the error I've attached, that is `/tmp/.mount_Kit-LiBQyWIv`.

What tipped me off is the line in `STDERR.log` that points to a read-only file system. 

When I take a look at this path, it is owned `root:root`, even though I executed the file as `mstine`. I tried becoming `root` and changing the ownership, but the OS will not allow it. So it appears to truly be a read-only FS.

I hope this additional context helps.

**Comment by TAKANOME-DEV** [comment]
@mstine  I was able to run it on ubuntu 22.04. Checkout the discussion -> https://github.com/johnlindquist/kit/discussions/121#discussioncomment-4766021

**Comment by johnlindquist** [comment]
@TAKANOME-DEV Fyi, I'm working on extracting the install process so people can run 

🚨 NOT READY YET, HOPEFULLY TOMORROW 🚨
```
npx @johnlindquist/install-kit
```

If the app install encounters an error.

**Comment by TAKANOME-DEV** [comment]
Awesome 🥳 That would be really helpful for folks so they can avoid spending hours googling stuff to make it work (like me :sweat_smile: )

**Comment by johnlindquist** [comment]
@TAKANOME-DEV Yeah, sorry about that 😬

The plan is to use it internally in the app setup so that if it fails, people can use it externally and it's the _extact same process_, but they get to debug/send PRs/etc.

**Comment by TAKANOME-DEV** [comment]
@johnlindquist 
Not related to this issue but before opening an issue for a feature request, I want to know if/how I can render an SVG in markdown preview. 
```js
await arg(
  "Doing something..",
  data.map((notif) => {
    return {
      name: md(`![Icon](<svg></svg>) ${notif.repository.full_name}`), // return <div></div>
      preview: async () => {
      // some async operations here...
         const res = md(`# ![Icon](<svg></svg>) ${notif.subject.title} \n\n ${comments}`) // return  ![Icon](<svg></svg>) + some text
         const res = md(`# <img src="some svg here" alt="" /> ${notif.subject.title} \n\n ${comments}`) // return  <img src="some svg here" alt="" />  + some text
        return res
      }
    };
  })
);
```
I'm using octicons to generate an SVG and I want to render it in the markdown.

**Comment by mstine** [comment]
> @mstine I was able to run it on ubuntu 22.04. Checkout the discussion -> [#121 (reply in thread)](https://github.com/johnlindquist/kit/discussions/121#discussioncomment-4766021)

Got it - I will give this a try. Thanks!
