### ISSUE TITLE
Running into Errors right after start the application

### ISSUE THREAD

**Issue by YoonJongok** [johnlindquist/kit#1033]
```
TypeError: Object has been destroyed
    at /Volumes/Kit 1.40.62-arm64/Kit.app/Contents/Resources/app.asar/main.prod.js:2:120073
    at l (/Volumes/Kit 1.40.62-arm64/Kit.app/Contents/Resources/app.asar/main.prod.js:2:100762)
    at Generator.<anonymous> (/Volumes/Kit 1.40.62-arm64/Kit.app/Contents/Resources/app.asar/main.prod.js:2:102100)
    at Generator.next (/Volumes/Kit 1.40.62-arm64/Kit.app/Contents/Resources/app.asar/main.prod.js:2:101125)
    at Ni (/Volumes/Kit 1.40.62-arm64/Kit.app/Contents/Resources/app.asar/main.prod.js:2:106754)
    at a (/Volumes/Kit 1.40.62-arm64/Kit.app/Contents/Resources/app.asar/main.prod.js:2:106958)
    at /Volumes/Kit 1.40.62-arm64/Kit.app/Contents/Resources/app.asar/main.prod.js:2:107019
    at new Promise (<anonymous>)
    at /Volumes/Kit 1.40.62-arm64/Kit.app/Contents/Resources/app.asar/main.prod.js:2:106898
    at /Volumes/Kit 1.40.62-arm64/Kit.app/Contents/Resources/app.asar/main.prod.js:2:120726
```

---

Kit 1.40.62
Electron 22.0.0
darwin 22.2.0
Locale: ko

**Comment by YoonJongok** [comment]
Hello, I am reporting this error because that's what it told me to. I would like to use this app and hope someone can help me out to fix this errors :)

**Comment by johnlindquist** [comment]
Hi @YoonJongok !

Did you drag the app to the /Applications dir?

Also, try just quitting and re-opening. That seemed to fix it over here:

https://github.com/johnlindquist/kit/issues/1002
