### ISSUE TITLE
Getting this error while trying to install the SDK on a windows machine. I think this is something to do with the space in username. Any workaround please?

### ISSUE THREAD

**Issue by MelodyGhost** [johnlindquist/kit#1040]
```
Error: spawn C:\Users\MG Rahim\AppData\Local\Programs\kit\resources\fallbacks\windows\clipboard_x86_64.exe ENOENT
    at r (C:\Users\MG Rahim\AppData\Local\Programs\kit\resources\app.asar\main.prod.js:2:543688)
    at n (C:\Users\MG Rahim\AppData\Local\Programs\kit\resources\app.asar\main.prod.js:2:543859)
    at ChildProcess.e.emit (C:\Users\MG Rahim\AppData\Local\Programs\kit\resources\app.asar\main.prod.js:2:544000)
    at Process.ChildProcess._handle.onexit (node:internal/child_process:291:12)
```

---

Kit 1.40.62
Electron 22.0.0
win32 10.0.22000
Locale: en-US

**Comment by winfried-van-loon-goudse** [comment]
Got the same issue, but without the space:

```
Unhandled Promise Rejection
Error: spawn C:/Users/wloon/AppData/Local/Programs/kit/resources/fallbacks/windows/clipboard_x86_64.exe ENOENT
    at r (C:/Users/wloon/AppData/Local/Programs/kit/resources/app.asar/main.prod.js:2:543688)
    at n (C:/Users/wloon/AppData/Local/Programs/kit/resources/app.asar/main.prod.js:2:543859)
    at ChildProcess.e.emit (C:/Users/wloon/AppData/Local/Programs/kit/resources/app.asar/main.prod.js:2:544000)
    at Process.ChildProcess._handle.onexit (node:internal/child_process:291:12)
```

**Comment by johnlindquist** [comment]
@MelodyGhost Can you try this version please?

https://github.com/johnlindquist/kitapp/releases/tag/v1.40.65

Also, see this post if that fails:

https://github.com/johnlindquist/kit/discussions/1052

**Comment by MelodyGhost** [comment]
Thanks, it is installed successfully with this new v1.40.65. Great work BTW <3

> @MelodyGhost Can you try this version please?
> 
> https://github.com/johnlindquist/kitapp/releases/tag/v1.40.65
> 
> Also, see this post if that fails:
> 
> #1052
