### ISSUE TITLE
Failure to install the windows preview version

### ISSUE THREAD

**Issue by onionhead0708** [johnlindquist/kit#1043]
```
Error: spawn C:\Users\raymond.chiu\AppData\Local\Programs\kit\resources\fallbacks\windows\clipboard_x86_64.exe ENOENT
    at r (C:\Users\raymond.chiu\AppData\Local\Programs\kit\resources\app.asar\main.prod.js:2:543688)
    at n (C:\Users\raymond.chiu\AppData\Local\Programs\kit\resources\app.asar\main.prod.js:2:543859)
    at ChildProcess.e.emit (C:\Users\raymond.chiu\AppData\Local\Programs\kit\resources\app.asar\main.prod.js:2:544000)
    at Process.ChildProcess._handle.onexit (node:internal/child_process:291:12)
```

---

Kit 1.40.62
Electron 22.0.0
win32 10.0.19044
Locale: en-US

**Comment by xenoxsis** [comment]
I got the same error - Running the npx command listed on the top of this: https://github.com/johnlindquist/kit/issues/1056 worked for me.

However, upon restarting kit, I get the same error when just opening the program. It seems to look for a kit\resources\fallbacks\windows\clipboard_x86_64.exe file, however I don't see the resources directory. Can you confirm?

**Comment by johnlindquist** [comment]
@xenoxsis Can you check your logs at:

```
~/Library/Logs/Kit.app/main.log
```

The clipboard error is misleading because it's trying to copy the error from the logs to the clipboard.

**Comment by johnlindquist** [comment]
@xenoxsis Also, did you try the pre-release build? It fixed for this user: https://github.com/johnlindquist/kit/issues/1040#issuecomment-1404167114

Download from here:
https://github.com/johnlindquist/kitapp/releases/tag/v1.40.65
