### ISSUE TITLE
Error when using Windows Installer

### ISSUE THREAD

**Issue by xenoxsis** [johnlindquist/kit#1057]
```
Error: spawn C:\Users\xenox\AppData\Local\Programs\kit\resources\fallbacks\windows\clipboard_x86_64.exe ENOENT
    at r (C:\Users\xenox\AppData\Local\Programs\kit\resources\app.asar\main.prod.js:2:543688)
    at n (C:\Users\xenox\AppData\Local\Programs\kit\resources\app.asar\main.prod.js:2:543859)
    at ChildProcess.e.emit (C:\Users\xenox\AppData\Local\Programs\kit\resources\app.asar\main.prod.js:2:544000)
    at Process.ChildProcess._handle.onexit (node:internal/child_process:291:12)
```
[main.log](https://github.com/johnlindquist/kit/files/10502098/main.log)

---

Kit 1.40.62
Electron 22.0.0
win32 10.0.19045
Locale: en-US

**Comment by xenoxsis** [comment]
Edit: Changed the title - I read that there was an alternative to the windows installer (which gave this error), which was the npx command. This installed the kit fine and everything worked. So did a few commands.
I then had to restart my PC, and after restarting, kit gave the same error as the installer did. It tries to start kit, but then it gives this error and then just hangs in the tray on "starting".

I tried rebooting again and such, to no avail.

I then tried looking for the file at "C:\Users\xenox\AppData\Local\Programs\kit\resources\fallbacks\windows\clipboard_x86_64.exe" - however I found no resources directory.
