### ISSUE TITLE
Issues with scraping on MacOS - executable doesn't exist

### ISSUE THREAD

**Issue by heaversm** [johnlindquist/kit#1078]
Getting the below output when trying to run the sample code from [this tutorial](https://egghead.io/lessons/script-kit-scrape-a-website-on-a-schedule-with-script-kit).

Attaching a gif to document.
![kit-playwright](https://user-images.githubusercontent.com/520541/215671043-97ed40f6-a3cf-45ce-b88a-ad003525eec6.gif)

```
  

$ cd /Users/mheavers/.kit
[21:05:28.881] [info] 
    at async file:///Users/mheavers/.kenv/scripts/scrape-indice-repairabilite.js:10:19
    at global.scrapeSelector (file:///Users/mheavers/.kit/lib/browser.js:100:34)
╚═════════════════════════════════════════════════════════════════════════╝
║ <3 Playwright Team                                                      ║
║                                                                         ║
║     npx playwright install                                              ║
║                                                                         ║
║ Please run the following command to download new browsers:              ║
║ Looks like Playwright Test or Playwright was just installed or updated. ║
╔═════════════════════════════════════════════════════════════════════════╗
[21:05:28.877] [warn] browserType.launch: Executable doesn't exist at /Users/mheavers/Library/Caches/ms-playwright/chromium-1045/chrome-mac/Chromium.app/Contents/MacOS/Chromium
[21:05:28.876] [warn] ☠️ ERROR PROMPT SHOULD SHOW ☠️

$ cd /Users/mheavers/.kit
[21:00:25.901] [info] 

$ cd /Users/mheavers/.kit
[20:57:25.002] [info] 

$ cd /Users/mheavers/.kit
[20:57:09.674] [info] 
    at async file:///Users/mheavers/.kenv/scripts/scrape-indice-repairabilite.js:10:19
    at async global.scrapeSelector (file:///Users/mheavers/.kit/lib/browser.js:97:24)
    at async file:///Users/mheavers/.kit/api/npm.js:100:12
    at kenvImport (file:///Users/mheavers/.kit/api/npm.js:77:15)
[20:57:09.669] [warn] Error: Error: Could not find main module for playwright
[20:57:09.668] [warn] ☠️ ERROR PROMPT SHOULD SHOW ☠️

$ cd /Users/mheavers/.kit
[20:56:19.055] [info] 
    at async file:///Users/mheavers/.kenv/scripts/scrape-indice-repairabilite.js:10:19
    at async global.scrapeSelector (file:///Users/mheavers/.kit/lib/browser.js:97:24)
    at async file:///Users/mheavers/.kit/api/npm.js:100:12
    at kenvImport (file:///Users/mheavers/.kit/api/npm.js:77:15)
- /Users/mheavers/.kenv/node_modules/playwright-core/lib/inprocess.js
- /Users/mheavers/.kenv/node_modules/playwright-core/lib/inProcessFactory.js
- /Users/mheavers/.kenv/node_modules/playwright-core/lib/server/index.js
- /Users/mheavers/.kenv/node_modules/playwright-core/lib/server/registry/index.js
- /Users/mheavers/.kenv/node_modules/playwright-core/lib/server/registry/dependencies.js
Require stack:
[20:56:19.052] [warn] Error: Error: Cannot find module '../../../package.json'
[20:56:19.051] [warn] ☠️ ERROR PROMPT SHOULD SHOW ☠️

Ok. Exiting...
[20:53:27.293] [info] 

Ok. Exiting...
[20:53:11.338] [info] 

$ cd /Users/mheavers/.kit
[20:50:26.299] [info] 
    at async file:///Users/mheavers/.kenv/scripts/scrape-indice-repairabilite.js:10:19
    at async global.scrapeSelector (file:///Users/mheavers/.kit/lib/browser.js:97:24)
    at async file:///Users/mheavers/.kit/api/npm.js:100:12
    at kenvImport (file:///Users/mheavers/.kit/api/npm.js:77:15)
- /Users/mheavers/.kenv/node_modules/playwright-core/lib/inprocess.js
- /Users/mheavers/.kenv/node_modules/playwright-core/lib/inProcessFactory.js
- /Users/mheavers/.kenv/node_modules/playwright-core/lib/server/index.js
- /Users/mheavers/.kenv/node_modules/playwright-core/lib/server/registry/index.js
- /Users/mheavers/.kenv/node_modules/playwright-core/lib/utils/index.js
- /Users/mheavers/.kenv/node_modules/playwright-core/lib/utils/zipFile.js
Require stack:
[20:50:26.296] [warn] Error: Error: Cannot find module '../zipBundle'
[20:50:26.296] [warn] ☠️ ERROR PROMPT SHOULD SHOW ☠️

$ cd /Users/mheavers/.kit
[20:46:29.399] [info] 
    at async file:///Users/mheavers/.kenv/scripts/scrape-indice-repairabilite.js:10:19
    at async global.scrapeSelector (file:///Users/mheavers/.kit/lib/browser.js:97:24)
    at async file:///Users/mheavers/.kit/api/npm.js:100:12
    at kenvImport (file:///Users/mheavers/.kit/api/npm.js:77:15)
- /Users/mheavers/.kenv/node_modules/playwright-core/lib/inprocess.js
- /Users/mheavers/.kenv/node_modules/playwright-core/lib/inProcessFactory.js
- /Users/mheavers/.kenv/node_modules/playwright-core/lib/server/index.js
- /Users/mheavers/.kenv/node_modules/playwright-core/lib/server/registry/index.js
- /Users/mheavers/.kenv/node_modules/playwright-core/lib/server/registry/dependencies.js
Require stack:
[20:46:29.395] [warn] Error: Error: Cannot find module '../../../package.json'
[20:46:29.395] [warn] ☠️ ERROR PROMPT SHOULD SHOW ☠️

$ cd /Users/mheavers/.kit
[20:41:03.162] [info] 
    at async file:///Users/mheavers/.kenv/scripts/scrape-indice-repairabilite.js:10:19
    at global.scrapeSelector (file:///Users/mheavers/.kit/lib/browser.js:100:34)
╚═════════════════════════════════════════════════════════════════════════╝
║ <3 Playwright Team                                                      ║
║                                                                         ║
║     npx playwright install                                              ║
║                                                                         ║
║ Please run the following command to download new browsers:              ║
║ Looks like Playwright Test or Playwright was just installed or updated. ║
╔═════════════════════════════════════════════════════════════════════════╗
[20:41:03.158] [warn] browserType.launch: Executable doesn't exist at /Users/mheavers/Library/Caches/ms-playwright/chromium-1045/chrome-mac/Chromium.app/Contents/MacOS/Chromium
[20:41:03.157] [warn] ☠️ ERROR PROMPT SHOULD SHOW ☠️

$ cd /Users/mheavers/.kit
[16:36:45.416] [info] 

$ cd /Users/mheavers/.kit
[16:34:54.536] [info] 
    at async file:///Users/mheavers/.kenv/scripts/scrape-indice-repairabilite.js:10:19
    at global.scrapeSelector (file:///Users/mheavers/.kit/lib/browser.js:100:34)
╚═════════════════════════════════════════════════════════════════════════╝
║ <3 Playwright Team                                                      ║
║                                                                         ║
║     npx playwright install                                              ║
║                                                                         ║
║ Please run the following command to download new browsers:              ║
║ Looks like Playwright Test or Playwright was just installed or updated. ║
╔═════════════════════════════════════════════════════════════════════════╗
[16:34:54.533] [warn] browserType.launch: Executable doesn't exist at /Users/mheavers/Library/Caches/ms-playwright/chromium-1045/chrome-mac/Chromium.app/Contents/MacOS/Chromium
[16:34:54.533] [warn] ☠️ ERROR PROMPT SHOULD SHOW ☠️

```

**Comment by hiddenboox** [comment]
Hi, same issue here, just follow what error say. `npx playwright install` should work as expected
