### ISSUE TITLE
Getting error on mac every 30 mins

### ISSUE THREAD

**Issue by avj2352** [johnlindquist/kit#1101]
```
TypeError: Object has been destroyed
    at BrowserWindow.s.reload (node:electron/js2c/browser_init:2:11004)
    at fo (/Applications/Kit.app/Contents/Resources/app.asar/main.prod.js:2:123696)
    at PowerMonitor.<anonymous> (/Applications/Kit.app/Contents/Resources/app.asar/main.prod.js:2:113273)
    at PowerMonitor.emit (node:events:525:35)
```

---

Kit 1.40.62
Electron 22.0.0
darwin 22.3.0
Locale: en-GB

**Comment by johnlindquist** [comment]
Does it still work?

Try quitting Kit.app then re-opening. I bet it will fix it.

Each time your computer wakes from sleep, Kit.app reloads the window UI to a clean start. The error reads like it's trying to reload a cached window that somehow was destroyed. I'll have to investigate what could cause that
