### ISSUE TITLE
I updated node/npm, and now Kit is unable to run any scripts

### ISSUE THREAD

**Issue by SimplGy** [johnlindquist/kit#1104]
I was in a state where script kit could run the intro script, but nothing with an NPM dependency. So, I updated that stuff.

Now, it can't even run the intro script. So, I wonder if changing the default version of node/npm breaks things. I'm sorry I don't, but I have no idea how to get it into a correct state again. 

## Background

The commands I ran to update the node environment were something like:

```
nvm install --latest-npm   
nvm install --lts
nvm alias default lts/hydrogen
```

I'm looking for a "re-run setup procedure" option maybe?

### Current State Error Output

Run this very simple intro script:
![image](https://user-images.githubusercontent.com/548809/216799982-6a0876ad-e6fa-4e37-afef-893cfde59cbf.png)

Get this error:
![image](https://user-images.githubusercontent.com/548809/216799992-7fbb6044-aa51-4c82-9294-6aa40c77d159.png)

```
Cannot find package '/Users/eric/.kenv/node_modules/@johnlindquist/kit/' imported from /Users/eric/.kenv/scripts/browse-scriptkit.js
Error [ERR_MODULE_NOT_FOUND]: Cannot find package '/Users/eric/.kenv/node_modules/@johnlindquist/kit/' imported from /Users/eric/.kenv/scripts/browse-scriptkit.js
    at new NodeError (node:internal/errors:387:5)
    at legacyMainResolve (node:internal/modules/esm/resolve:341:9)
    at packageResolve (node:internal/modules/esm/resolve:944:14)
    at moduleResolve (node:internal/modules/esm/resolve:1006:20)
    at defaultResolve (node:internal/modules/esm/resolve:1220:11)
    at nextResolve (node:internal/modules/esm/loader:165:28)
    at ESMLoader.resolve (node:internal/modules/esm/loader:844:30)
    at ESMLoader.getModuleJob (node:internal/modules/esm/loader:431:18)
    at ModuleWrap.<anonymous> (node:internal/modules/esm/module_job:76:40)
    at link (node:internal/modules/esm/module_job:75:36)
```

**Comment by SimplGy** [comment]
Noting that in finder, `/Users/eric/.kenv/node_modules/@johnlindquist/kit/` appears to be an empty folder

**Comment by johnlindquist** [comment]
@SimplGy the ~/.kenv/package.json should show "@johnlindquist/kit" pointing to ~/.kit

It should be using node from ~/.knode/bin/node regardless of what version of node you have installed elsewhere.

If you want to "reset" the Kit.app:

1. Quit
2. Delete ~/.kit and ~/.knode
3. Open Kit.app and it should go through the install process again

**Comment by le250055** [comment]
Getting a similar issue
[2023-02-07 16:25:08.618] [warn] ☠️ ERROR PROMPT SHOULD SHOW ☠️
[2023-02-07 16:25:08.619] [warn] Error [ERR_MODULE_NOT_FOUND]: Cannot find package '@johnlindquist/kit' imported from /private/var/folders/14/sk4mzw5s1h9gz1dc2xmgbvc80000gq/T/kit/myfile.mjs
    at new NodeError (node:internal/errors:387:5)
    at packageResolve (node:internal/modules/esm/resolve:957:9)
    at moduleResolve (node:internal/modules/esm/resolve:1006:20)
    at defaultResolve (node:internal/modules/esm/resolve:1220:11)
    at nextResolve (node:internal/modules/esm/loader:165:28)
    at ESMLoader.resolve (node:internal/modules/esm/loader:844:30)
    at ESMLoader.getModuleJob (node:internal/modules/esm/loader:431:18)
    at ModuleWrap.<anonymous> (node:internal/modules/esm/module_job:76:40)
    at link (node:internal/modules/esm/module_job:75:36)

**Comment by johnlindquist** [comment]
@le250055 Did anything happen before this error started occurring that you think may have caused it?

**Comment by SimplGy** [comment]
> the ~/.kenv/package.json should show "@johnlindquist/kit" pointing to ~/.kit

Confirmed, looks right:

```sh
➜  .kenv  cat package.json 
{
  "type": "module",
  "devDependencies": {
    "@johnlindquist/kit": "file:../.kit",
    "image-downloader": "^4.3.0",
    "sharp": "^0.31.3"
  }
}
```

`~/.kit` is not an empty folder, so not sure why I'm seeing `Cannot find package '/Users/eric/.kenv/node_modules/@johnlindquist/kit/`

> It should be using node from ~/.knode/bin/node regardless of what version of node you have installed elsewhere.

Ah, good to see how this works. Confirmed.

```sh
-rwxr-xr-x  1 eric  staff    79M Sep 22 20:39 node
lrwxr-xr-x  1 eric  staff    38B Feb  4 18:09 npm -> ../lib/node_modules/npm/bin/npm-cli.js
lrwxr-xr-x  1 eric  staff    38B Feb  4 18:09 npx -> ../lib/node_modules/npm/bin/npx-cli.js
➜  bin  ./node -v
v16.17.1
➜  bin  ./npm -v
8.15.0
➜  bin  npm -v
9.3.1
➜  bin  node -v
v18.14.0
```

## Trying the reset procedure...

```
➜  ~  rm -rf ~/.kit 
➜  ~  rm -rf ~/.knode 
```

2. Restarted the app (noted that it does re-run the setup procedure)
3. Still see the error noted in the original issue, even for the two line `browse(url)` script

**Comment by johnlindquist** [comment]
@SimplGy If you manually link ~/.kit to ~/.kenv like so:

```bash
cd ~/.kenv && PATH=~/.knode/bin:$PATH npm i ~/.kit
```

Does that:
1. Succedd?
2. Change what the `~/.kenv/package.json` looks like?

**Comment by SimplGy** [comment]
```sh
➜  $  cd ~/.kenv
➜  $  PATH=~/.knode/bin:$PATH npm i ~/.kit
npm ERR! code ENOTDIR
npm ERR! syscall rename
npm ERR! path /Users/eric/.kenv/node_modules/@johnlindquist/kit
npm ERR! dest /Users/eric/.kenv/node_modules/@johnlindquist/.kit-XKBdfT1i
npm ERR! errno -20
npm ERR! ENOTDIR: not a directory, rename '/Users/eric/.kenv/node_modules/@johnlindquist/kit' -> '/Users/eric/.kenv/node_modules/@johnlindquist/.kit-XKBdfT1i'

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/eric/.npm/_logs/2023-02-11T20_14_15_190Z-debug-0.log
```

...looking

**Comment by johnlindquist** [comment]
@SimplGy Now I'm _really_ curious 😅

(fyi, that npm i command works on my machine 🙃)

**Comment by SimplGy** [comment]
Back in a working state! 🎉

I think it was `rm -rf ~/.kenv/node_modules` that fixed it, although I also deleted `package-lock.json` at some point too.

Wish I could tell you what the problem was, these environment issue must be a real challenge. 
Really appreciate the help and look forward to building some amazing automations with this tool.

**Comment by johnlindquist** [comment]
@SimplGy Hrmmmmmmmmmmm 🤔

By any chance, did you ever use `yarn` inside of `~/.kenv`?

**Comment by SimplGy** [comment]
No, not on purpose/manually.

I haven't used yarn in a long time and I'm sure of that because I can't remember what it's for. 😁

**Comment by johnlindquist** [comment]
@SimplGy I really appreciate you taking the time to look into it!!! 🙏

Glad we at least have a fix for now.

The setup process literally does `npm i ~/.kit` just like we did above.

I'm curious if installing `sharp` or `image-downloader` caused some strange npm side effect. I can't think of what else may have impacted it...

**Comment by vhmartinezm** [comment]
Hey @johnlindquist I have a similar issue. I updated to node 18.12.1. I installed canvas and d3-node and I have a weird behavior. My others scripts run in both launcher and cli. But the one which uses canvas works only in the cli. If I run it from the app I got:

[08:32:03.105] [warn] ☠️ ERROR PROMPT SHOULD SHOW ☠️
[08:32:02.970] [info] Found d3-node in /Users/victormartinezmejias/.kenv/package.json

$ cd ~/.kit
[08:27:27.980] [info] 
    at async file:///~/.kenv/scripts/generate-graph.js:5:16
    at kenvImport (file:///~/.kit/api/npm.js:77:15)
the module (for instance, using `npm rebuild` or `npm install`).
[113. Please try re-compiling or re-installing
[108. This version of Node.js requires
was compiled against a different Node.js version using
[08:27:27.978] [warn] Error: Error: The module '~/.kenv/node_modules/canvas/build/Release/canvas.node'

Do they run different?

**Comment by johnlindquist** [comment]
@vhmartinezm I'll get this sorted in this week's build.

It's a matter of the script running from the app's node vs the ~/.knode/bin/node.

I made the change to run on the app's node because Windows would show a spinner any time your launch ~/.knode/bin/node. I may end up adding a metadata like below to force the app to use knode:

```js
// Node: ~/.kit/bin/node
```

Not sure yet, but it ll be fixed soon.

**Comment by vhmartinezm** [comment]
@johnlindquist thank you for your answer. I like the metadata definition. I'll be waiting

**Comment by vhmartinezm** [comment]
Hey @johnlindquist! Any news on this topic in the latest version (1.53.22)?

**Comment by johnlindquist** [comment]
@vhmartinezm Should be sorted 👍

**Comment by vhmartinezm** [comment]
@johnlindquist worked perfect, thanks!
