### ISSUE TITLE
getTabs error in Arc Browser

### ISSUE THREAD

**Issue by juanvera** [johnlindquist/kit#1118]
When I tried to perform getTabs on the Arc browser I received this error:

[08:40:42.859] [info] 
    at async file:///Users/user/.kenv/scripts/save-tabs.js:5:12
    at process.processTicksAndRejections (node:internal/process/task_queues:96:5)
    at global.getTabs (file:///Users/user/.kit/lib/browser.js:62:17)
    at JSON.parse (<anonymous>)
[08:40:42.850] [warn] SyntaxError: Unexpected end of JSON input
[08:40:42.850] [warn] ☠️ ERROR PROMPT SHOULD SHOW ☠️

**Comment by johnlindquist** [comment]
Did you see my comment here?

https://github.com/johnlindquist/kit/discussions/418#discussioncomment-4946368
