### ISSUE TITLE
App crashes when the main window is destroyed by macOS

### ISSUE THREAD

**Issue by matjahs** [johnlindquist/kit#1133]
The crash below happened after macOS destroyed the main app window because it got interrupted by another program. I to no extent an Electron expert, that being said: it looks like it might have to do with an event listener that is still holding a reference to the window that got destroyed by the OS?

```
TypeError: Object has been destroyed
    at /Applications/Kit.app/Contents/Resources/app.asar/main.prod.js:2:130211
    at l (/Applications/Kit.app/Contents/Resources/app.asar/main.prod.js:2:110839)
    at Generator.<anonymous> (/Applications/Kit.app/Contents/Resources/app.asar/main.prod.js:2:112177)
    at Generator.next (/Applications/Kit.app/Contents/Resources/app.asar/main.prod.js:2:111202)
    at co (/Applications/Kit.app/Contents/Resources/app.asar/main.prod.js:2:116831)
    at a (/Applications/Kit.app/Contents/Resources/app.asar/main.prod.js:2:117035)
    at /Applications/Kit.app/Contents/Resources/app.asar/main.prod.js:2:117096
    at new Promise (<anonymous>)
    at /Applications/Kit.app/Contents/Resources/app.asar/main.prod.js:2:116975
    at /Applications/Kit.app/Contents/Resources/app.asar/main.prod.js:2:130864
```

[2023-02-18 16:18:42.031] [info] kenv found
[2023-02-18 16:18:42.031] [info] node found
[2023-02-18 16:18:42.031] [info] node found
[2023-02-18 16:18:42.031] [info] node_modules found
[2023-02-18 16:18:42.031] [info] node_modules found
[2023-02-18 16:18:42.031] [info] kenv is configured
[2023-02-18 16:18:42.031] [info] kenv .env found
[2023-02-18 16:18:42.031] [info] Install verified
[2023-02-19 16:46:20.633] [info] 🪟 window-all-closed

Kit 1.48.0
Electron 22.0.3
darwin 22.3.0
Locale: en-GB

**Comment by Varkoff** [comment]
Hi @matjahs did you solve this issue by any chance ? I got the same error after modifying the Kit settings.

**Comment by matjahs** [comment]
> Hi @matjahs did you solve this issue by any chance ? I got the same error after modifying the Kit settings. 

@Varkoff I ended up completely removing Kit and reinstalling the app.
