### ISSUE TITLE
Linux: TypeError [ERR_INVALID_ARG_TYPE]: The "file" argument must be of type string. Received undefined

### ISSUE THREAD

**Issue by brpaz** [johnlindquist/kit#1136]
Hello. Really cool to be able to use ScriptKit in Linux.

I can start kit from the command line just fine, but I got errors in some commands.  For example: "Edit env" or "Open Logs" commands.

```bash
TypeError [ERR_INVALID_ARG_TYPE]: The "file" argument must be of type string. Received undefined
    at new NodeError (node:internal/errors:387:5)
    at validateString (node:internal/validators:121:11)
    at normalizeSpawnArguments (node:child_process:518:3)
    at spawn (node:child_process:706:13)
    at global.edit (file:///home/bruno/.kit/target/terminal.js:209:19)
    at file:///home/bruno/.kit/cli/env.js?uuid=3a864111-21f2-4fc5-bf49-65d06d615940:1:1
    at ModuleJob.run (node:internal/modules/esm/module_job:193:25)
    at async Promise.all (index 0)
    at async ESMLoader.import (node:internal/modules/esm/loader:533:24)
    at async global.attemptImport (file:///home/bruno/.kit/api/kit.js:173:28) {
  code: 'ERR_INVALID_ARG_TYPE'
}
```

On the command `switch to js/js` got a different error:

``` bash
ReferenceError: mainScript is not defined
    at file:///home/bruno/.kit/cli/switch-to-js.js?uuid=1eb80111-2b21-45d6-8c91-b2571d71059a:4:1
```

**Comment by brpaz** [comment]
This happened because of a missing global variable. Reinstalling script kit fixed the issue
