### ISSUE TITLE
window beta starting problem

### ISSUE THREAD

**Issue by yesfeel** [johnlindquist/kit#1144]
```
Error: spawn C:\Users\jp.hwang\AppData\Local\Programs\kit\resources\fallbacks\windows\clipboard_x86_64.exe ENOENT
    at r (C:\Users\jp.hwang\AppData\Local\Programs\kit\resources\app.asar\main.prod.js:2:553520)
    at n (C:\Users\jp.hwang\AppData\Local\Programs\kit\resources\app.asar\main.prod.js:2:553691)
    at ChildProcess.e.emit (C:\Users\jp.hwang\AppData\Local\Programs\kit\resources\app.asar\main.prod.js:2:553832)
    at Process.ChildProcess._handle.onexit (node:internal/child_process:291:12)
```

    at ClientRequest.<anonymous> (C:\Users\jp.hwang\AppData\Local\Programs\kit\resources\app.asar\main.prod.js:2:865411)
    at Object.onceWrapper (node:events:628:26)
    at ClientRequest.emit (node:events:513:28)
    at TLSSocket.socketErrorListener (node:_http_client:481:9)
    at TLSSocket.emit (node:events:513:28)
    at emitErrorNT (node:internal/streams/destroy:157:8)
    at emitErrorCloseNT (node:internal/streams/destroy:122:3)
    at processTicksAndRejections (node:internal/process/task_queues:83:21)
[2023-02-27 08:42:17.639] [info] WebContents Focus

Kit 1.48.0
Electron 22.0.3
win32 10.0.19045
Locale: ko

**Comment by johnlindquist** [comment]
@yesfeel Can you show me your log at:

%USERPROFILE%\AppData\Roaming\Kit\logs\main.log
