### ISSUE TITLE
Linux: App browser and removing script from inside of kit

### ISSUE THREAD

**Issue by AyushSehrawat** [johnlindquist/kit#1147]
OS: Ubuntu 22.10

```
Error: exec() failed: No such file or directory
    at new UnixTerminal (/tmp/.mount_Kit-LiUvn15n/resources/app.asar/node_modules/node-pty/src/unixTerminal.ts:115:22)
    at Object.spawn (/tmp/.mount_Kit-LiUvn15n/resources/app.asar/node_modules/node-pty/src/index.ts:30:10)
    at /tmp/.mount_Kit-LiUvn15n/resources/app.asar/main.prod.js:2:281777
    at l (/tmp/.mount_Kit-LiUvn15n/resources/app.asar/main.prod.js:2:273627)
    at Generator.<anonymous> (/tmp/.mount_Kit-LiUvn15n/resources/app.asar/main.prod.js:2:274965)
    at Generator.next (/tmp/.mount_Kit-LiUvn15n/resources/app.asar/main.prod.js:2:273990)
    at Kl (/tmp/.mount_Kit-LiUvn15n/resources/app.asar/main.prod.js:2:280650)
    at a (/tmp/.mount_Kit-LiUvn15n/resources/app.asar/main.prod.js:2:283329)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
```

[2023-03-03 14:19:55.845] [info] Verifying ~/.kenv exists:
[2023-03-03 14:19:55.847] [info] kenv found
[2023-03-03 14:19:55.849] [info] node found
[2023-03-03 14:19:55.851] [info] node found
[2023-03-03 14:19:55.855] [info] node_modules found
[2023-03-03 14:19:55.858] [info] node_modules found
[2023-03-03 14:19:55.860] [info] kenv is configured
[2023-03-03 14:19:55.862] [info] kenv .env found
[2023-03-03 14:19:55.863] [info] Install verified

Kit 1.48.0
Electron 22.0.3
linux 5.19.0-35-generic
Locale: en-GB

**Comment by AyushSehrawat** [comment]
![image](https://user-images.githubusercontent.com/69469790/222680404-3fbcd1c4-2820-4479-b553-aea7e97f7790.png)

No input works, just this screen

**Comment by AyushSehrawat** [comment]
Also an issue with app launcher 

```
Command failed with exit code 127: /usr/bin/mdfind -onlyin / "kind:application"
/bin/sh: 1: /usr/bin/mdfind: not found
Error: Command failed with exit code 127: /usr/bin/mdfind -onlyin / "kind:application"
/bin/sh: 1: /usr/bin/mdfind: not found
    at makeError (file:///home/mini/.kit/node_modules/@johnlindquist/globals/dist/index.js:28:111641)
    at file:///home/mini/.kit/node_modules/@johnlindquist/globals/dist/index.js:28:123014
    at process.processTicksAndRejections (node:internal/process/task_queues:96:5)
```

**Comment by AyushSehrawat** [comment]
Issue with remove too, when trying to remove a script from kit with ctrl shift backspace ```
ENOENT: no such file or directory, mkdir '/var/snap/firefox/common/host-hunspell/.Trash-1000'
Error: ENOENT: no such file or directory, mkdir '/var/snap/firefox/common/host-hunspell/.Trash-1000'
```

![image](https://user-images.githubusercontent.com/69469790/222681685-722460a2-5cec-4322-930e-3533f712788c.png)

**Comment by AyushSehrawat** [comment]
Update : Fixed terminal issue by setting `KIT_SHELL=bash` in the `~/.kenv/env`
