### ISSUE TITLE
getTabs: Unexpected token in JSON at position 1845  at JSON.parse

### ISSUE THREAD

**Issue by re4388** [johnlindquist/kit#1286]
this is my script:
```typescript
let currentTabs: Tab[] = await getTabs();
const url = `https://mail.google.com/mail/u/0/#chat/welcome`;
const pattern = /WeMo Corp. 郵件/;
goToTab(pattern, currentTabs, url);

async function goToTab(
  regMatchTerm: RegExp,
  curTabs: Tab[],
  fallBackUrl?: string
) {
  const matchedTabs = curTabs.filter((tab) => regMatchTerm.test(tab.title));
  if (matchedTabs.length > 0) {
    focusTab(matchedTabs[0].url);
  } else {
    if (fallBackUrl === undefined) {
      await div(md(`no url provided, no need to open it if we cannot find it`));
      return;
    }
    browse(fallBackUrl);
  }
}

```

this is the error log
```
[08:28:37.101] [warn]  ☠️ ERROR PROMPT SHOULD SHOW ☠️
[08:28:37.102] [warn]  SyntaxError: Unexpected token   in JSON at position 1845
    at JSON.parse (<anonymous>)
    at global.getTabs (file:///Users/re4388/.kit/lib/browser.js:62:17)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async file:///Users/re4388/.kenv/.scripts/go-to-mr-hermes.mjs:16:19



[08:29:32.566] [warn]  ☠️ ERROR PROMPT SHOULD SHOW ☠️
[08:29:32.566] [warn]  SyntaxError: Unexpected token   in JSON at position 1845
    at JSON.parse (<anonymous>)
    at global.getTabs (file:///Users/re4388/.kit/lib/browser.js:62:17)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async file:///Users/re4388/.kenv/.scripts/go-to-mr-hermes.mjs:16:19

```
After checking the file  at /Users/re4388/.kit/lib/browser.js (I guess this might be the root cause?)
and then I tried to run the script in my script editor

![image](https://github.com/johnlindquist/kit/assets/5414334/4baaab5f-08ac-472c-8a20-3417fe473658)

the result of the apple script:
```
"[{\"url\":\"https://www.figma.com/file/8GORW3KqwUKkyB1QrXCMf7/Apollo?type=design&node-id=1565-517&t=SAeZzUt5MfCe5Cj1-0\",\"title\":\"Apollo – Figma\"},{\"url\":\"https://mail.google.com/mail/u/0/#chat/space/AAAADnWCuZI\",\"title\":\"WeMo PASS 兌換序號 - TWM 合作案 - Chat\"},{\"url\":\"https://docs.google.com/document/d/1M_O69ph0kp6T8_weJyu8cMalDiHyO1SWmZm57Wonmzs/edit#heading=h.jea2b2pqnt32\",\"title\":\"WeMo PASS 兌換序號 - TWM 合作案 - Google 文件\"},{\"url\":\"https://docs.google.com/document/d/1-oJ2WgM24T9gJoP9NEmjey12sQCxt5IiypA3K8pqV1s/edit#heading=h.a3z464v6oihu\",\"title\":\"WeMo Pass 1.0 BE Planning - Google 文件\"},{\"url\":\"https://docs.google.com/document/d/1uPTwjJpQzRVX5eS6c7lBsIPugBVvyHFu1xrHQNLs_bA/edit#heading=h.78rfzao3je2c\",\"title\":\"WeMo Pass Discount - 特殊方案擴充 - Google 文件\"},{\"url\":\"https://docs.google.com/document/d/1uPTwjJpQzRVX5eS6c7lBsIPugBVvyHFu1xrHQNLs_bA/edit#heading=h.r3tgvtt46t2g\",\"title\":\"WeMo Pass Discount - 特殊方案擴充 - Google 文件\"},{\"url\":\"https://github.com/easychen/howto-make-more-money\",\"title\":\"easychen/howto-make-more-money: 程序员如何优雅的挣零花钱，2.0版，升级为小书了。Most of this not work outside China , so no English translate\"},{\"url\":\"https://github.com/amplication/amplication\",\"title\":\"amplication/amplication: 🔥🔥🔥 Open-source backend development platform. Build production-ready services without wasting time on repetitive coding.\"},{\"url\":\"https://github.com/immersive-translate/immersive-translate\",\"title\":\"immersive-translate/immersive-translate: 沉浸式双语网页翻译扩展 , 支持输入框翻译， 鼠标悬停翻译， PDF, Epub, 字幕文件, TXT 文件翻译 - Immersive Dual Web Page Translation Extension\"},{\"url\":\"https://github.com/trending/Javascript?since=weekly\",\"title\":\"Trending JavaScript repositories on GitHub this week\"},{\"url\":\"https://github.com/qeeqbox/social-analyzer\",\"title\":\"qeeqbox/social-analyzer: API, CLI, and Web App for analyzing and finding a person's profile in 1000 social media \\ websites\"},{\"url\":\"https://github.com/goldbergyoni/nodebestpractices#-71-dont-block-the-event-loop\",\"title\":\"goldbergyoni/nodebestpractices: :white_check_mark: The Node.js best practices list (May 2023)\"},{\"url\":\"https://github.com/Mintplex-Labs/anything-llm\",\"title\":\"Mintplex-Labs/anything-llm: A full-stack application that turns any documents into an intelligent chatbot with a sleek UI and easier way to manage your workspaces.\"},{\"url\":\"https://github.com/sindresorhus/awesome-nodejs#books\",\"title\":\"sindresorhus/awesome-nodejs: :zap: Delightful Node.js packages and resources\"},{\"url\":\"https://github.com/CurtisSlone/Node-Design-Patterns-Exercises/blob/main/05-Exercises/5.3-producerconsumer/index.js\",\"title\":\"Node-Design-Patterns-Exercises/05-Exercises/5.3-producerconsumer/index.js at main · CurtisSlone/Node-Design-Patterns-Exercises · GitHub\"},{\"url\":\"chrome://newtab/\",\"title\":\"New Tab\"},{\"url\":\"https://www.npmjs.com/package/level\",\"title\":\"level - npm\"},{\"url\":\"https://pjchender.dev/nodejs/node-path/\",\"title\":\"[node] Path Module | PJCHENder 未整理筆記\"},{\"url\":\"chrome://newtab/\",\"title\":\"New Tab\"},{\"url\":\"chrome://history/\",\"title\":\"Activity | Better History\"},{\"url\":\"https://github.com/johnlindquist/kit/issues\",\"title\":\"Issues · johnlindquist/kit\"},{\"url\":\"https://github.com/johnlindquist/kit/issues?q=is%3Aissue+is%3ASyntaxError%3A+Unexpected+token\",\"title\":\"Issues · johnlindquist/kit\"},{\"url\":\"https://github.com/johnlindquist/kit/issues/1056\",\"title\":\"My Install Failed. What Should I Do? · Issue #1056 · johnlindquist/kit\"},{\"url\":\"https://github.com/johnlindquist/kit/issues/662\",\"title\":\"getTabs throw \\\"Unexpected end of JSON input\\\" · Issue #662 · johnlindquist/kit\"}]"
```

and I copy the result and it indeed have the similiar error:
![image](https://github.com/johnlindquist/kit/assets/5414334/5cfac282-1f75-43ba-8ddd-f282c6b7f820)

Or maybe this is about my particular case of this result? maybe some format is not able to parse ? (although I use online JSON validation tool to check and it said the above result is correct)

PS: not sure if my node version (v18.12.1 ) in .kenv folder is relevant

**Comment by johnlindquist** [comment]
@re4388 Looks like this sequence is breaking it

```
media \\ websites
```

So the title of the website is using escape characters causing the JSON to break.

I'll add in something like this for a silly workaround:
```
.replaceAll(`\\ `, '')
```

**Comment by re4388** [comment]
Thanks a lot! Just cannot see this...
I will just walk around it! XD
