### ISSUE TITLE
`editor` Error `'Uncaught Error: Language id "vs.editor.nullLanguage" is not configured nor known\n'`

### ISSUE THREAD

**Issue by Schmedu** [johnlindquist/kit#1293]
Here's an error that occurred now a couple of times for me.

To replicate take this script:
```
// Name: debug-editor-language

import "@johnlindquist/kit"

await editor({
    name: "hello",
    input: `
// Name: debug-editor-language

import "@johnlindquist/kit"

await editor({
    name: "hello",
    input: `
Normal Code block:
\`\`\`
# TODO
\`\`\`

Code Block with specified language 
\`\`\`bash
#!/bin/bash 
# TODO
\`\`\`
`
})
```

And then try to go down with the cursor to the second code block to `#!/bin/bash`, when you reach there the window closes and it throws an error:
```
[2023-06-30 09:55:38.890] [info]  👓 Focus bounds: { x: 480, y: 173, width: 768, height: 640 }
[2023-06-30 09:55:41.486] [info]  {
  type: 'error',
  message: 'Uncaught Error: Language id "vs.editor.nullLanguage" is not configured nor known\n' +
    '\n' +
    'Error: Language id "vs.editor.nullLanguage" is not configured nor known\n' +
    '    at g (file:///Applications/Kit.app/Contents/Resources/assets/vs/editor/editor.main.js:569:67518)\n' +
    '    at c.getLanguageConfiguration (file:///Applications/Kit.app/Contents/Resources/assets/vs/editor/editor.main.js:569:67218)\n' +
    '    at u.getLanguageConfiguration (file:///Applications/Kit.app/Contents/Resources/assets/vs/editor/editor.main.js:181:93344)\n' +
    '    at u.getWordAtPosition (file:///Applications/Kit.app/Contents/Resources/assets/vs/editor/editor.main.js:181:93657)\n' +
    '    at Mt.getWordAtPosition (file:///Applications/Kit.app/Contents/Resources/assets/vs/editor/editor.main.js:689:10802)\n' +
    '    at B._getWord (file:///Applications/Kit.app/Contents/Resources/assets/vs/editor/editor.main.js:744:42643)\n' +
    '    at B._run (file:///Applications/Kit.app/Contents/Resources/assets/vs/editor/editor.main.js:744:42835)\n' +
    '    at B._onPositionChanged (file:///Applications/Kit.app/Contents/Resources/assets/vs/editor/editor.main.js:744:42536)\n' +
    '    at file:///Applications/Kit.app/Contents/Resources/assets/vs/editor/editor.main.js:744:40375\n' +
    '    at t.invoke (file:///Applications/Kit.app/Contents/Resources/assets/vs/editor/editor.main.js:58:145)',
  filename: 'file:///Applications/Kit.app/Contents/Resources/assets/vs/editor/editor.main.js',
  lineno: 6,
  colno: 117807,
  error: 'Error: Language id "vs.editor.nullLanguage" is not configured nor known\n' +
    '\n' +
    'Error: Language id "vs.editor.nullLanguage" is not configured nor known\n' +
    '    at g (file:///Applications/Kit.app/Contents/Resources/assets/vs/editor/editor.main.js:569:67518)\n' +
    '    at c.getLanguageConfiguration (file:///Applications/Kit.app/Contents/Resources/assets/vs/editor/editor.main.js:569:67218)\n' +
    '    at u.getLanguageConfiguration (file:///Applications/Kit.app/Contents/Resources/assets/vs/editor/editor.main.js:181:93344)\n' +
    '    at u.getWordAtPosition (file:///Applications/Kit.app/Contents/Resources/assets/vs/editor/editor.main.js:181:93657)\n' +
    '    at Mt.getWordAtPosition (file:///Applications/Kit.app/Contents/Resources/assets/vs/editor/editor.main.js:689:10802)\n' +
    '    at B._getWord (file:///Applications/Kit.app/Contents/Resources/assets/vs/editor/editor.main.js:744:42643)\n' +
    '    at B._run (file:///Applications/Kit.app/Contents/Resources/assets/vs/editor/editor.main.js:744:42835)\n' +
    '    at B._onPositionChanged (file:///Applications/Kit.app/Contents/Resources/assets/vs/editor/editor.main.js:744:42536)\n' +
    '    at file:///Applications/Kit.app/Contents/Resources/assets/vs/editor/editor.main.js:744:40375\n' +
    '    at t.invoke (file:///Applications/Kit.app/Contents/Resources/assets/vs/editor/editor.main.js:58:145)\n' +
    '    at file:///Applications/Kit.app/Contents/Resources/assets/vs/editor/editor.main.js:6:117821'
}
[2023-06-30 09:55:41.488] [info]  AppChannel.ERROR_RELOAD
[2023-06-30 09:55:41.488] [info]  Reloading prompt window...
```

**Comment by Schmedu** [comment]
I tried to add `language: "markdown"` to the editor, but this still did not work

**Comment by johnlindquist** [comment]
@Schmedu Looks like I'll be able to handle this internally:

```js
monaco.languages.register({ id: 'vs.editor.nullLanguage' });
monaco.languages.setLanguageConfiguration('vs.editor.nullLanguage', {});
```

This way, when it dynamically swaps to an unregistered language (like in your demo it's trying to swap to "bash" language support), it will just fallback to "plain text" editing.

**Comment by Schmedu** [comment]
That should work out, I close the issue therefore

**Comment by Schmedu** [comment]
✔️
