### ISSUE TITLE
Crashing after update to 2.0.15

### ISSUE THREAD

**Issue by ndrake** [johnlindquist/kit#1393]
Kit indicated it had an updated available. I clicked the menubar item to install the update.  It spent time doing stuff and it seemed to update ok.  Now, when I attempt to run ScriptKit it crashes with `Kit quit unexpectantly`.  

I'm running ScriptKit on an M1 Max Macbook Pro. Once interesting thing, the crash report says `Code Type: X86-64 (Translated)` but I'm pretty sure I installed the M1 version of ScriptKit.

Here are the log messages from main.log when I attempt to run ScriptKit (by clicking on the Kit icon in my Applications folder)

```

🟢🟢 🟢  !!!SCRIPT KIT TIME!!! 🟢 🟢 🟢
[2023-12-10 09:09:38.230] [info]  Setting up process.env
[2023-12-10 09:09:38.375] [info]  Appending switch: ignore-certificate-errors
[2023-12-10 09:09:38.377] [info]  Prefs: {
  appDb: {
    version: '0.0.0',
    openAtLogin: true,
    previewScripts: true,
    autoUpdate: true,
    tray: true,
    authorized: false,
    searchDebounce: true,
    termFont: 'monospace',
    convertKeymap: true,
    cachePrompt: true,
    mini: false,
    disableGpu: false,
    disableBlurEffect: false
  }
}
[2023-12-10 09:09:38.682] [info]
Release channel: dev
Arch: x64
Platform: darwin
Node version: v18.18.2
Node path: /Users/natedrake/.knode/bin/node
Electron version: 28.0.0
Electron Node version: 18.18.2
Electron Chromium version: 120.0.6099.56
Electron execPath: /Applications/Kit.app/Contents/MacOS/Kit

[2023-12-10 09:09:40.028] [info]  🎨 Creating tray...
[2023-12-10 09:09:40.031] [info]  🎨 Tray icon: busy
[2023-12-10 09:09:40.217] [info]  Tray created
[2023-12-10 09:09:40.219] [info]  🧐 Checking /Users/natedrake/.kit {
  cwd: '/Users/natedrake/.kit',
  encoding: 'utf-8',
  env: {
    KIT: '/Users/natedrake/.kit',
    KENV: '/Users/natedrake/.kenv',
    PATH: '/Users/natedrake/.knode/bin:/Users/natedrake/.kit/bin:/Users/natedrake/.kit/override/code:/Users/natedrake/.kenv/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin'
  },
  stdio: 'pipe'
}
[2023-12-10 09:09:40.354] [info]  📋 Clipboard store initialized: object
[2023-12-10 09:09:41.007] [info]  👩‍💻 Reading app.json {
  version: '1.79.5',
  openAtLogin: true,
  previewScripts: true,
  autoUpdate: true,
  tray: true,
  authorized: false,
  searchDebounce: true,
  termFont: 'monospace',
  convertKeymap: true,
  cachePrompt: true,
  mini: false,
  disableGpu: false,
  disableBlurEffect: false
}
[2023-12-10 09:09:43.984] [info]
---------------------------
📺 Renderer process started
---------------------------

[2023-12-10 09:09:44.358] [info]  📁 Asset path: /Applications/Kit.app/Contents/Resources/assets/svg/logo.svg
[2023-12-10 09:09:44.547] [info]  👩‍💻 UI changed to: arg
[2023-12-10 09:09:44.989] [info]  Send user.json to prompt {}
[2023-12-10 09:09:45.054] [info]  Toggle prompt env: KIT_MAIN_SCRIPT to undefined
[2023-12-10 09:09:45.055] [info]  { isDarkState: 'false', isDarkNative: 'false' }
[2023-12-10 09:09:45.058] [info]  👀 No themes configured in .env. Using defaults
[2023-12-10 09:09:45.059] [info]  🎨 Convert Colors: {
  foreground: '2C2C2C',
  accent: '2F86D3',
  background: 'white',
  opacity: '0.5',
  ui: '204, 204, 204',
  'ui-bg-opacity': '0.5',
  'ui-border-opacity': '0.5',
  vibrancy: 'popover',
  appearance: 'light'
}
[2023-12-10 09:09:45.062] [info]  🫥 Theme opacity: 0.5
[2023-12-10 09:09:45.063] [info]  💄 Setting appearance to light
[2023-12-10 09:09:45.064] [info]  Prompt window created
[2023-12-10 09:09:45.068] [info]

---------------------------------
[2023-12-10 09:09:45.073] [info]  Launching Script Kit  2.0.15
[2023-12-10 09:09:45.074] [info]  auto updater detected version: 2.0.15
[2023-12-10 09:09:45.075] [info]  PATH: /Users/natedrake/.knode/bin:/Users/natedrake/.kit/bin:/Users/natedrake/.kit/override/code:/Users/natedrake/.kenv/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/bin
[2023-12-10 09:09:45.081] [info]  Checking online status...
[2023-12-10 09:09:45.108] [info]  event: did-stop-loading
[2023-12-10 09:09:45.118] [info]  🗼 Status: Online
[2023-12-10 09:09:45.124] [info]  Didn't find /Users/natedrake/.kit/.kitignore
[2023-12-10 09:09:46.538] [info]  👀 Status: {"status":"default","message":""}
[2023-12-10 09:09:46.539] [info]  🎨 Tray status: default
[2023-12-10 09:09:46.539] [info]  🎨 Tray icon: default
[2023-12-10 09:09:46.549] [info]  Stored version: 0.0.0
[2023-12-10 09:09:46.550] [info]  /Users/natedrake/.kit
[2023-12-10 09:09:46.551] [info]  kit not found
[2023-12-10 09:09:46.551] [info]  🌑 shouldUseDarkColors: false
[2023-12-10 09:09:46.551] [info]  🎨 Convert Colors: {
  foreground: '2C2C2C',
  accent: '2F86D3',
  background: 'white',
  opacity: '0.5',
  ui: '204, 204, 204',
  'ui-bg-opacity': '0.5',
  'ui-border-opacity': '0.5',
  vibrancy: 'popover',
  appearance: 'light'
}
[2023-12-10 09:09:46.552] [info]  🫥 Theme opacity: 0.5
[2023-12-10 09:09:46.552] [info]  💄 Setting appearance to light
[2023-12-10 09:09:46.553] [info]  -1 setScript { script: '__app__/splash-screen' }
[2023-12-10 09:09:46.555] [info]  🌊 Showing Splash Install Screen
[2023-12-10 09:09:46.556] [info]  function: setPromptAlwaysOnTop: false
[2023-12-10 09:09:46.563] [info]  👀 Ignore blur: true
[2023-12-10 09:09:46.605] [info]  Setting uiAtom to splash
[2023-12-10 09:09:46.614] [info]  Message match: 0.8118388217796946
[2023-12-10 09:09:46.615] [info]  Before initBounds
[2023-12-10 09:09:46.616] [info]  ↖ Init bounds: Prompt splash ui { x: 501, y: 173, width: 768, height: 480 }
[2023-12-10 09:09:46.624] [info]  After initBounds
[2023-12-10 09:09:46.948] [info]  🔥 Starting Kit First Install
[2023-12-10 09:09:46.949] [info]  node found
[2023-12-10 09:09:46.950] [info]  👍 Node Exists
[2023-12-10 09:09:47.085] [info]  existingNode v18.18.2, execPath: v18.18.2

[2023-12-10 09:09:47.086] [info]  node found
[2023-12-10 09:09:47.094] [info]  🤔 Stored version: 0.0.0 -> Current version: 2.0.15. Semver match? false
[2023-12-10 09:09:47.094] [info]  Requires install: true
[2023-12-10 09:09:47.096] [info]  /Users/natedrake/.kit
[2023-12-10 09:09:47.097] [info]  kit not found
[2023-12-10 09:09:47.099] [info]  /Users/natedrake/.kit
[2023-12-10 09:09:47.100] [info]  kit not found
[2023-12-10 09:09:47.101] [info]  .kit doesn't exist or isn't on a contributor branch
[2023-12-10 09:09:47.102] [info]  kitTar: /Applications/Kit.app/Contents/Resources/assets/kit.tar.gz
[2023-12-10 09:09:47.110] [info]  fileAssets: IconTemplate.png,IconTemplate@2x-update.png,IconTemplate@2x.png,assets.d.ts,base,dev-app-update.yml,editor,entitlements.mac.plist,icon.icns,icon.png,icons8-file-48.png,icons8-file-50.png,icons8-gif-48.png,icons8-image-file-24.png,kit_url_darwin_x64.txt,language,loader.js,menu,node.txt,package.json,petite-vue.es.js,release_channel.txt,svg,tray,version.txt,vs,yarn.lock
[2023-12-10 09:09:47.116] [info]  📦 Kit file doesn't exist at /Applications/Kit.app/Contents/Resources/assets/kit.tar.gz
[2023-12-10 09:09:47.234] [info]  📁 Asset path: /Applications/Kit.app/Contents/Resources/assets/icon.png
[2023-12-10 09:09:47.377] [info]  👩‍💻 UI changed to: splash
[2023-12-10 09:09:47.777] [info]  function: setPromptAlwaysOnTop: true
[2023-12-10 09:09:47.778] [info]  📌 on top: true. ignoreBlur: true
[2023-12-10 09:09:47.782] [info]  WebContents Focus
[2023-12-10 09:09:47.783] [info]  WebContents Focus
[2023-12-10 09:09:47.784] [info]  📌 always-on-top-changed: true
[2023-12-10 09:09:47.785] [info]  👆 Always on top changed: on
[2023-12-10 09:09:47.790] [info]  Prompt window in bounds.
[2023-12-10 09:09:48.065] [info]  function: setPromptAlwaysOnTop: true
[2023-12-10 09:09:48.147] [info]  😳 Prompt window shown
[2023-12-10 09:09:48.377] [error] HTTPError: Response code 404 (Not Found)
    at EventEmitter.<anonymous> (/Applications/Kit.app/Contents/Resources/app.asar/main.prod.js:8:383246)
    at EventEmitter.emit (node:events:517:28)
    at /Applications/Kit.app/Contents/Resources/app.asar/main.prod.js:8:381221
    at Immediate.<anonymous> (/Applications/Kit.app/Contents/Resources/app.asar/main.prod.js:8:381311)
    at processImmediate (node:internal/timers:476:21)
[2023-12-10 09:09:48.400] [warn]  Response code 404 (Not Found)
[2023-12-10 09:09:48.400] [warn]  HTTPError: Response code 404 (Not Found)
    at EventEmitter.<anonymous> (/Applications/Kit.app/Contents/Resources/app.asar/main.prod.js:8:383246)
    at EventEmitter.emit (node:events:517:28)
    at /Applications/Kit.app/Contents/Resources/app.asar/main.prod.js:8:381221
    at Immediate.<anonymous> (/Applications/Kit.app/Contents/Resources/app.asar/main.prod.js:8:381311)
    at processImmediate (node:internal/timers:476:21)
[2023-12-10 09:09:48.410] [info]  .kit installed
[2023-12-10 09:09:48.411] [info]  /Users/natedrake/.kit: 👷 /Users/natedrake/.knode/bin/npm i esbuild@0.19.5 --save-exact --production --prefer-dedupe --loglevel=verbose
[2023-12-10 09:09:48.435] [info]  Hide reason: Destroy
[2023-12-10 09:09:48.442] [info]  Attempt Hide: Destroy
[2023-12-10 09:09:48.443] [info]  🙈 Hiding prompt window
[2023-12-10 09:09:48.448] [info]  📌 closed
[2023-12-10 09:09:48.450] [info]  🪟 window-all-closed
```

Here are the contents of the crash report that OS X prompts me to send to Apple:

[sk_crash.txt](https://github.com/johnlindquist/kit/files/13628082/sk_crash.txt)

**Comment by johnlindquist** [comment]
The updater crossed wires with the Ubuntu build for a couple hours last night. 

You can grab the latest mac build here:

https://github.com/johnlindquist/kitapp/releases/tag/v2.0.27

**Comment by ndrake** [comment]
Yep.  After I wrote this up I looked at discord and saw you already address it.  Using the 2.0.27 build is working for me.
Thanks!
