### ISSUE TITLE
Can't connect to github when installing behind GFW.

### ISSUE THREAD

**Issue by ekilzen** [johnlindquist/kit#88]
I think it does not use system proxy setting.

```
Cloning into '/Users/like/.kenv'...
fatal: unable to access 'https://github.com/johnlindquist/kenv.git/': Failed to connect to github.com port 443: Operation timed out

Error: Cloning into '/Users/like/.kenv'...
fatal: unable to access 'https://github.com/johnlindquist/kenv.git/': Failed to connect to github.com port 443: Operation timed out

    at t.GitExecutorChain.onFatalException (/Applications/Kit.app/Contents/Resources/app.asar/main.prod.js:8:1167952)
    at t.GitExecutorChain.<anonymous> (/Applications/Kit.app/Contents/Resources/app.asar/main.prod.js:8:1167830)
    at Generator.throw (<anonymous>)
    at a (/Applications/Kit.app/Contents/Resources/app.asar/main.prod.js:8:1166674)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
[2021-03-28 19:45:36.906] [info] /Applications/Kit.app/Contents/MacOS/Kit undefined
[2021-03-28 19:45:37.351] [info] Checking if kit exists
[2021-03-28 19:45:37.361] [info] ~/.kit not found. Installing...
[2021-03-28 19:45:58.207] [info] Adding node to ~/.kit...
[2021-03-28 19:46:57.425] [info] install node   Configuration
> Version:  v15.12.0 (resolved from )
> Prefix:   node
> Platform: darwin
> Arch:     x64

> Tarball URL: https://nodejs.org/dist/v15.12.0/node-v15.12.0-darwin-x64.tar.gz
> Installing Node.js, please wait…
✓ Done

[2021-03-28 19:46:57.427] [info] adding ~/.kit packages...
[2021-03-28 19:47:05.059] [info] npm 
added 116 packages, and audited 117 packages in 6s

14 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities

[2021-03-28 19:47:05.060] [info] Comparing versions...
[2021-03-28 19:47:05.469] [info] ~/.kit: 1.1.0-beta.79
 - Kit app: 1.1.0-beta.79
[2021-03-28 19:47:05.887] [info] Currently on branch: main

[2021-03-28 19:47:05.888] [info] Checking out 1.1.0-beta.79
[2021-03-28 19:47:05.889] [info] git fetch all tags
[2021-03-28 19:48:29.241] [warn] fatal: unable to access 'https://github.com/johnlindquist/kit.git/': LibreSSL SSL_connect: SSL_ERROR_SYSCALL in connection to github.com:443 
error: Could not fetch origin

[2021-03-28 19:48:29.252] [warn] Error: fatal: unable to access 'https://github.com/johnlindquist/kit.git/': LibreSSL SSL_connect: SSL_ERROR_SYSCALL in connection to github.com:443 
error: Could not fetch origin

    at t.GitExecutorChain.onFatalException (/Applications/Kit.app/Contents/Resources/app.asar/main.prod.js:8:1167952)
    at t.GitExecutorChain.<anonymous> (/Applications/Kit.app/Contents/Resources/app.asar/main.prod.js:8:1167830)
    at Generator.throw (<anonymous>)
    at a (/Applications/Kit.app/Contents/Resources/app.asar/main.prod.js:8:1166674)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
[2021-03-28 19:48:29.903] [warn] Object has been destroyed
[2021-03-28 19:48:29.904] [warn] TypeError: Object has been destroyed
    at Bt (/Applications/Kit.app/Contents/Resources/app.asar/main.prod.js:2:45431)
    at Gt (/Applications/Kit.app/Contents/Resources/app.asar/main.prod.js:2:46246)
    at /Applications/Kit.app/Contents/Resources/app.asar/main.prod.js:2:47741
    at l (/Applications/Kit.app/Contents/Resources/app.asar/main.prod.js:8:1052623)
    at Generator._invoke (/Applications/Kit.app/Contents/Resources/app.asar/main.prod.js:8:1052411)
    at Generator.next (/Applications/Kit.app/Contents/Resources/app.asar/main.prod.js:8:1053048)
    at Tt (/Applications/Kit.app/Contents/Resources/app.asar/main.prod.js:2:41053)
    at s (/Applications/Kit.app/Contents/Resources/app.asar/main.prod.js:2:41257)
[2021-03-28 19:48:42.188] [info] /Applications/Kit.app/Contents/MacOS/Kit undefined
[2021-03-28 19:48:42.548] [info] Checking if kit exists
[2021-03-28 19:48:42.549] [info] Comparing versions...
[2021-03-28 19:48:42.862] [info] ~/.kit: 1.1.0-beta.79
 - Kit app: 1.1.0-beta.79
[2021-03-28 19:48:43.157] [info] Currently on branch: main

[2021-03-28 19:48:43.158] [info] Checking out 1.1.0-beta.79
[2021-03-28 19:48:43.158] [info] git fetch all tags
[2021-03-28 19:48:44.296] [info] git checkout tags/1.1.0-beta.79
[2021-03-28 19:48:44.633] [info] Run .kenv setup script...
[2021-03-28 19:50:00.525] [warn] Cloning into '/Users/like/.kenv'...
fatal: unable to access 'https://github.com/johnlindquist/kenv.git/': Failed to connect to github.com port 443: Operation timed out

[2021-03-28 19:50:00.537] [warn] Error: Cloning into '/Users/like/.kenv'...
fatal: unable to access 'https://github.com/johnlindquist/kenv.git/': Failed to connect to github.com port 443: Operation timed out

    at t.GitExecutorChain.onFatalException (/Applications/Kit.app/Contents/Resources/app.asar/main.prod.js:8:1167952)
    at t.GitExecutorChain.<anonymous> (/Applications/Kit.app/Contents/Resources/app.asar/main.prod.js:8:1167830)
    at Generator.throw (<anonymous>)
    at a (/Applications/Kit.app/Contents/Resources/app.asar/main.prod.js:8:1166674)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
```

**Comment by johnlindquist** [comment]
Oh, thanks for reporting this!

I'll try to use scutil to read user's proxy settings into an env var during install. I'll probably get around to it sometime this week.

**Comment by johnlindquist** [comment]
@ekilzen if you'd like to try the manual process while waiting for me to fix this, you can find the steps here:

[Manual Installation Instructions](https://github.com/johnlindquist/kit/discussions/89)

**Comment by johnlindquist** [comment]
I removed the git requirement from recent builds. This should no longer happen. 👍
