### ISSUE TITLE
Crash when launching prompt (or any other function) in 1.30.8 [Mac OS Ventura beta 7]

### ISSUE THREAD

**Issue by titouv** [johnlindquist/kit#902]
```
Error: Channel closed
    at new NodeError (node:internal/errors:371:5)
    at ChildProcess.target.send (node:internal/child_process:741:16)
    at /Applications/Kit.app/Contents/Resources/app.asar/main.prod.js:2:286376
    at u (/Applications/Kit.app/Contents/Resources/app.asar/main.prod.js:2:277721)
    at Generator._invoke (/Applications/Kit.app/Contents/Resources/app.asar/main.prod.js:2:277474)
    at Generator.next (/Applications/Kit.app/Contents/Resources/app.asar/main.prod.js:2:278084)
    at js (/Applications/Kit.app/Contents/Resources/app.asar/main.prod.js:2:283729)
    at a (/Applications/Kit.app/Contents/Resources/app.asar/main.prod.js:2:283933)
```

---

Kit 1.30.8
Electron 19.0.16
darwin 22.1.0
Locale: en-GB

**Comment by titouv** [comment]
I can add a video example of the crash if needed

**Comment by johnlindquist** [comment]
@titouv Does quitting Kit.app and opening it again fix it?

Also: can you please attach:

~/.kit/logs/kit.log
~/Library/Logs/Kit/main.log

The error means the script process is ending before Kit.app has a chance to communicate with it. I'll have to find a machine to install Ventura on to see what's happening...

**Comment by titouv** [comment]
I tried multiple things restarting (kit and the mac), clearing cache, reinstalling kit but nothing worked. 
https://user-images.githubusercontent.com/39600279/193138338-4f3e9902-5bcb-4ca0-8469-f5a32ec0c0dd.mov

**Comment by johnlindquist** [comment]
@titouv Thanks for the efforts! I understand the nature of the error, but I'll need to see the logs to get a better idea of what could be causing it

**Comment by johnlindquist** [comment]
@titouv Another thing to try is to quit then attempt a re-install of the npm deps (using the ~/.knode npm):

```bash
cd ~/.kit
PATH=~/.knode/bin:$PATH npm i
```

**Comment by titouv** [comment]
Yes of course, sorry. This is the log that are generated each time I try to open the prompt

```
[2022-09-29 22:52:05.722] [info] 🎨 Tray icon: default
[2022-09-29 22:52:05.730] [info] Show App: /Users/titouanv/.kit/main/index.js
[2022-09-29 22:52:05.731] [info] 🏃‍♀️ Run /Users/titouanv/.kit/main/index.js
[2022-09-29 22:52:05.731] [warn] 🤔 Can't find idle Prompt Process. Starting another
[2022-09-29 22:52:05.734] [info] 5372: 🟢 start idle Prompt
[2022-09-29 22:52:05.906] [info] DISCONNECT
[2022-09-29 22:52:05.907] [info] EXIT { pid: 5372, code: 1 }
[2022-09-29 22:52:05.907] [info] 5372: 🟡 exit 1. Prompt process: 
[2022-09-29 22:52:05.907] [info] 5372: 🛑 removed
[2022-09-29 22:52:06.735] [info] 5372: 🏎 /Users/titouanv/.kit/main/index.js 
[2022-09-29 22:52:06.737] [info] Hours since sync: 2
[2022-09-29 22:52:06.740] [info] 5373: 🟢 start idle Prompt
[2022-09-29 22:52:06.741] [warn] Uncaught Exception: Channel closed
[2022-09-29 22:52:06.742] [warn] Error: Channel closed
    at new NodeError (node:internal/errors:371:5)
    at ChildProcess.target.send (node:internal/child_process:741:16)
    at /Applications/Kit.app/Contents/Resources/app.asar/main.prod.js:2:286376
    at u (/Applications/Kit.app/Contents/Resources/app.asar/main.prod.js:2:277721)
    at Generator._invoke (/Applications/Kit.app/Contents/Resources/app.asar/main.prod.js:2:277474)
    at Generator.next (/Applications/Kit.app/Contents/Resources/app.asar/main.prod.js:2:278084)
    at js (/Applications/Kit.app/Contents/Resources/app.asar/main.prod.js:2:283729)
    at a (/Applications/Kit.app/Contents/Resources/app.asar/main.prod.js:2:283933)
[2022-09-29 22:52:06.742] [error] Error: Channel closed
    at new NodeError (node:internal/errors:371:5)
    at ChildProcess.target.send (node:internal/child_process:741:16)
    at /Applications/Kit.app/Contents/Resources/app.asar/main.prod.js:2:286376
    at u (/Applications/Kit.app/Contents/Resources/app.asar/main.prod.js:2:277721)
    at Generator._invoke (/Applications/Kit.app/Contents/Resources/app.asar/main.prod.js:2:277474)
    at Generator.next (/Applications/Kit.app/Contents/Resources/app.asar/main.prod.js:2:278084)
    at js (/Applications/Kit.app/Contents/Resources/app.asar/main.prod.js:2:283729)
    at a (/Applications/Kit.app/Contents/Resources/app.asar/main.prod.js:2:283933)
[2022-09-29 22:52:08.073] [info] DISCONNECT
[2022-09-29 22:52:08.073] [info] EXIT { pid: 5373, code: 1 }
[2022-09-29 22:52:08.074] [info] 5373: 🟡 exit 1. Prompt process: 
[2022-09-29 22:52:08.074] [info] 5373: 🛑 removed
```

**Comment by titouv** [comment]
I'm tried to reinstall npm as proposed but this is log (maybe I did something wrong)

```bash
npm ERR! code ENOTEMPTY
npm ERR! syscall rename
npm ERR! path /Users/titouanv/.kit/node_modules/@octokit/auth-oauth-device
npm ERR! dest /Users/titouanv/.kit/node_modules/@octokit/.auth-oauth-device-oH3LfFxE
npm ERR! errno -66
npm ERR! ENOTEMPTY: directory not empty, rename '/Users/titouanv/.kit/node_modules/@octokit/auth-oauth-device' -> '/Users/titouanv/.kit/node_modules/@octokit/.auth-oauth-device-oH3LfFxE'

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/titouanv/.npm/_logs/2022-09-29T20_53_42_929Z-debug-0.log````

**Comment by johnlindquist** [comment]
@titouv Hmm, delete the ~/.kit/node_modules dir and try it again.

**Comment by titouv** [comment]
Ok, this is working ! I don't know how this happen. I can give you more info about my config to reproduce if needed. I love the Kit project btw thanks for what you've made it (and for the help)

**Comment by johnlindquist** [comment]
@titouv Awesome, thanks for you patience. It's a standard `npm install`, so wifi off, network issues, CDN issues, etc, etc all could have interrupted it.
