### ISSUE TITLE
Attempting to Check for Update

### ISSUE THREAD

**Issue by SteveMattan** [johnlindquist/kit#916]
```
TypeError: Error processing argument at index 1, conversion failure from /Applications/Kit.app/Contents/Resources/assets/menu/update-Template.png
    at EventEmitter.a.insert (node:electron/js2c/browser_init:81:4026)
    at EventEmitter.a.append (node:electron/js2c/browser_init:81:3579)
    at node:electron/js2c/browser_init:81:5585
    at Array.forEach (<anonymous>)
    at Function.a.buildFromTemplate (node:electron/js2c/browser_init:81:5535)
    at /Applications/Kit.app/Contents/Resources/app.asar/main.prod.js:2:68915
    at u (/Applications/Kit.app/Contents/Resources/app.asar/main.prod.js:2:56700)
    at Generator._invoke (/Applications/Kit.app/Contents/Resources/app.asar/main.prod.js:2:56453)
    at Generator.next (/Applications/Kit.app/Contents/Resources/app.asar/main.prod.js:2:57063)
    at rt (/Applications/Kit.app/Contents/Resources/app.asar/main.prod.js:2:61937)
```

---

Kit 1.30.8
Electron 19.0.16
darwin 21.6.0
Locale: en-US

**Comment by johnlindquist** [comment]
Thanks, that's fixed in 1.30.22 👍

(Just a missing icon that's used in the menubar dropdown)
