### ISSUE TITLE
I tried to view my clipbord history and got the below error.

### ISSUE THREAD

**Issue by bigloudjeff** [johnlindquist/kit#928]
```
TypeError: Error processing argument at index 0, conversion failure from 
    at /Applications/Kit.app/Contents/Resources/app.asar/main.prod.js:2:280786
    at u (/Applications/Kit.app/Contents/Resources/app.asar/main.prod.js:2:247022)
    at Generator._invoke (/Applications/Kit.app/Contents/Resources/app.asar/main.prod.js:2:246775)
    at Generator.next (/Applications/Kit.app/Contents/Resources/app.asar/main.prod.js:2:247385)
    at Os (/Applications/Kit.app/Contents/Resources/app.asar/main.prod.js:2:252960)
    at a (/Applications/Kit.app/Contents/Resources/app.asar/main.prod.js:2:253164)
    at /Applications/Kit.app/Contents/Resources/app.asar/main.prod.js:2:253225
    at new Promise (<anonymous>)
    at /Applications/Kit.app/Contents/Resources/app.asar/main.prod.js:2:253104
    at /Applications/Kit.app/Contents/Resources/app.asar/main.prod.js:2:281132
```

---

Kit 1.32.4
Electron 19.0.16
darwin 22.1.0
Locale: en-US

**Comment by johnlindquist** [comment]
@bigloudjeff Was that from using `<` from the main menu or trying the `await getClipboardHistory()` in a script?

Have you seen any other issues?

**Comment by bigloudjeff** [comment]
It was using the "<" keyboard shortcut. I had not given scriptkit accessibility permissions yet.
