### ISSUE TITLE
Error while ScriptKit was in the background

### ISSUE THREAD

**Issue by prometheas** [johnlindquist/kit#936]
Scrubbing username from filesystem paths:

```
TypeError: Error processing argument at index 0, conversion failure from CommandOrControl
    at /Users/xxxx/Applications/Kit.app/Contents/Resources/app.asar/main.prod.js:2:313855
    at u (/Users/xxxx/Applications/Kit.app/Contents/Resources/app.asar/main.prod.js:2:306151)
    at Generator._invoke (/Users/xxxx/Applications/Kit.app/Contents/Resources/app.asar/main.prod.js:2:305904)
    at Generator.next (/Users/xxxx/Applications/Kit.app/Contents/Resources/app.asar/main.prod.js:2:306514)
    at yc (/Users/xxxx/Applications/Kit.app/Contents/Resources/app.asar/main.prod.js:2:311388)
    at a (/Users/xxxx/Applications/Kit.app/Contents/Resources/app.asar/main.prod.js:2:311592)
```

Perhaps source maps would useful for these stack traces 😅

---

Kit 1.32.8
Electron 19.0.16
darwin 21.6.0
Locale: en-US

**Comment by johnlindquist** [comment]
`CommandOrControl` is only used when dealing with keyboard shortcuts. Do you have any custom `// Shortcut` metadata in your scripts? My guess is that a shortcut isn't formatted correctly.



> stack traces

Yeah, I definitely need to improve the error prompt. It's just set to the defaults and I need to throw a bunch of errors at it now to make sure it's actually helpful 😅

**Comment by prometheas** [comment]
Actually, it kept happening, so I wound up removing the app. Thanks for your follow up and suggestion ❤️ closing.
