### ISSUE TITLE
Just installed Kit on Windows 11 Arm on a Parallels VM.

### ISSUE THREAD

**Issue by bigloudjeff** [johnlindquist/kit#938]
```
Error: spawn C:\Users\jefwes\AppData\Local\Programs\kit\resources\fallbacks\windows\clipboard_x86_64.exe ENOENT
    at n (C:\Users\jefwes\AppData\Local\Programs\kit\resources\app.asar\main.prod.js:2:452217)
    at r (C:\Users\jefwes\AppData\Local\Programs\kit\resources\app.asar\main.prod.js:2:452388)
    at ChildProcess.e.emit (C:\Users\jefwes\AppData\Local\Programs\kit\resources\app.asar\main.prod.js:2:452529)
    at Process.ChildProcess._handle.onexit (node:internal/child_process:291:12)
```

---

Kit 1.32.8
Electron 19.0.16
win32 10.0.22623
Locale: en-US

Let me know what I can do to help resolve the issue.

**Comment by johnlindquist** [comment]
I haven't done any testing on Windows arm or VMs. I don't really have the bandwidth to dig into them for awhile unfortunately

**Comment by bigloudjeff** [comment]
I'll do some digging around and see if I can maybe see what's going on. If I come up with anything I will let you know. Thanks!

**Comment by johnlindquist** [comment]
I'm 90% sure I'd have to publish a Windows arm build for it to even have a chance of working...

**Comment by tbogard** [comment]
@johnlindquist Check electron 22, it might have updated how you publish stuff to ARM, also the build system changed completely.

**Comment by ecrax** [comment]
I have the same error during the install, but on a "normal" x86 Windows Machine:
```
Unhandled Promise Rejection
Error: spawn C:/Users/Leo/AppData/Local/Programs/kit/resources/fallbacks/windows/clipboard_x86_64.exe ENOENT
    at r (C:/Users/Leo/AppData/Local/Programs/kit/resources/app.asar/main.prod.js:2:543688)
    at n (C:/Users/Leo/AppData/Local/Programs/kit/resources/app.asar/main.prod.js:2:543859)
    at ChildProcess.e.emit (C:/Users/Leo/AppData/Local/Programs/kit/resources/app.asar/main.prod.js:2:544000)
    at Process.ChildProcess._handle.onexit (node:internal/child_process:291:12)
```

After dismissing the error, the installer is stuck at "kenv .env found".

**Comment by gabrielcarloto** [comment]
I have the same issue as ecrax

**Comment by johnlindquist** [comment]
@tbogard It's on Electron 22 on the latest build. There's an arm build here (https://github.com/johnlindquist/kitapp/releases/download/v1.40.62/Kit-Windows-1.40.62-arm64.exe), but I don't have a machine to test it on:

https://github.com/johnlindquist/kitapp/releases/tag/v1.40.62

@ecrax @gabrielcarloto 

Can you please try this fix and see if it works for you?

https://github.com/johnlindquist/kit/issues/984#issuecomment-1379993381

**Comment by gabrielcarloto** [comment]
@johnlindquist it worked 🎉 thank you

**Comment by johnlindquist** [comment]
@gabrielcarloto Awesome! I'm curious why it's a different behavior/permissions for different people. 

## Why the `spawn` error?
The setup process is trying copy the _real_ error to clipboard, but failing. So it's a secondary issue that masks the first. (This is a Windows only issue that I simply never ran into)

## The real error
Script Kit bundles a node version that matches the Electron node version and sets it up under `~/.knode`. This is by unzipping node, then renaming the dir. The error is happening here:

https://github.com/johnlindquist/kitapp/blob/main/src/main.dev.ts#L897

I need to find a way to reproduce to confirm a fix. I _think_ I can chmod the dir before trying to rename it, but won't know until I try it.

**Comment by ecrax** [comment]
> @tbogard It's on Electron 22 on the latest build. There's an arm build here (https://github.com/johnlindquist/kitapp/releases/download/v1.40.62/Kit-Windows-1.40.62-arm64.exe), but I don't have a machine to test it on:
> 
> https://github.com/johnlindquist/kitapp/releases/tag/v1.40.62
> 
> @ecrax @gabrielcarloto 
> 
> Can you please try this fix and see if it works for you?
> 
> https://github.com/johnlindquist/kit/issues/984#issuecomment-1379993381

I will try it as soon as I can (propably tomorrow :/) 

Thanks for your work :)
