### ISSUE TITLE
Error Switching to Typescript Mode

### ISSUE THREAD

**Issue by antoniogiroz** [johnlindquist/kit#947]
<img width="768" alt="image" src="https://user-images.githubusercontent.com/520071/201713046-8df89af0-b6e6-4abe-a861-1690b73a1473.png">

I can see this error in the log:

```
[17:29:35.695] [info] Prompt window in bounds.
[17:29:34.694] [info] ↖ Bounds: Prompt arg ui { x: 1120, y: 233, width: 768, height: 480 }
    at process.processTicksAndRejections (node:internal/process/task_queues:96:5)
    at file:///Users/agil/.kit/main/kit.js:9:7
    at run (file:///Users/agil/.kit/core/utils.js:407:26)
    at resolveToScriptPath (file:///Users/agil/.kit/core/utils.js:164:11)
[17:29:34.682] [warn] Error: /Users/agil/.kit/cli/cli/switch-to-ts.js not found
[17:29:34.682] [warn] ☠️ ERROR PROMPT SHOULD SHOW ☠️
[17:29:34.680] [info] 39726: Prompt #3 complete 👍
[17:29:34.679] [info] 39726: Value submitted ✅ 
[17:29:32.742] [info] Prompt window in bounds.
[17:29:31.737] [info] ↖ Bounds: Prompt arg ui { x: 1120, y: 233, width: 768, height: 480 }
[17:29:31.708] [info] 39726: Prompt #2 complete 👍
[17:29:31.441] [info] Prompt window in bounds.
[17:29:30.474] [info] 40436: 🟢 start idle Prompt
[17:29:30.473] [info] 👶 Create child Prompt process  []
[17:29:30.437] [info] ↖ Bounds: Prompt arg ui { x: 1120, y: 233, width: 768, height: 480 }
[17:29:30.433] [info] 39726: Prompt #1 complete 👍
[17:29:30.427] [info] ↖ Bounds: Prompt arg ui { x: 1120, y: 233, width: 768, height: 480 }
[17:29:30.390] [info] Hours since sync: 0
[17:29:30.370] [info] 📄 scriptPath changed: /Users/agil/.kit/main/index.js
[17:29:30.370] [info] Hours since sync: 0
[17:29:30.369] [info] 39726: 🏎 /Users/agil/.kit/main/index.js 
[17:29:30.368] [info] 🏃‍♀️ Run /Users/agil/.kit/main/index.js
[17:29:30.368] [info] 🏚  main shortcut
[17:29:16.430] [info] ↖ Bounds: Prompt none ui { x: 1120, y: 233, width: 768, height: 480 }
[17:29:16.429] [info] 39580: 🛑 removed
[17:29:16.429] [info] 39580: 🟡 exit 0. Prompt process: /Users/agil/.kit/cli/error-action.js
[17:29:16.428] [info] EXIT { pid: 39580, code: 0 }
[17:29:16.420] [info] DISCONNECT
[17:29:15.267] [info] 🫣 App hidden
[17:29:15.254] [info] Opening /Users/agil/.kit/logs/kit.log with /usr/local/bin/code
[17:29:15.246] [info] 😳 Hiding app
[17:29:15.224] [info] 39580: Prompt #4 complete 👍
[17:29:15.223] [info] 39580: Value submitted ✅ 
[17:29:10.290] [info] Prompt window in bounds.
[17:29:09.287] [info] ↖ Bounds: Prompt arg ui { x: 1120, y: 233, width: 768, height: 480 }
    at process.processTicksAndRejections (node:internal/process/task_queues:96:5)
    at file:///Users/agil/.kit/main/kit.js:9:7
    at run (file:///Users/agil/.kit/core/utils.js:407:26)
    at resolveToScriptPath (file:///Users/agil/.kit/core/utils.js:164:11)
[17:29:09.271] [warn] Error: /Users/agil/.kit/cli/cli/switch-to-ts.js not found
[17:29:09.270] [warn] ☠️ ERROR PROMPT SHOULD SHOW ☠️
[17:29:09.269] [info] 39580: Prompt #3 complete 👍
[17:29:09.269] [info] 39580: Value submitted ✅ 
[17:29:07.897] [info] Prompt window in bounds.
[17:29:06.893] [info] ↖ Bounds: Prompt arg ui { x: 1120, y: 233, width: 768, height: 480 }
[17:29:06.859] [info] 39580: Prompt #2 complete 👍
[17:29:01.318] [info] Prompt window in bounds.
[17:29:00.356] [info] 40373: 🟢 start idle Prompt
[17:29:00.355] [info] 👶 Create child Prompt process  []
[17:29:00.317] [info] ↖ Bounds: Prompt arg ui { x: 1120, y: 233, width: 768, height: 480 }
[17:29:00.314] [info] 39580: Prompt #1 complete 👍
[17:29:00.310] [info] ↖ Bounds: Prompt arg ui { x: 1120, y: 233, width: 768, height: 480 }
[17:29:00.274] [info] Hours since sync: 0
[17:29:00.256] [info] 📄 scriptPath changed: /Users/agil/.kit/main/index.js
[17:29:00.255] [info] Hours since sync: 0
[17:29:00.254] [info] 39580: 🏎 /Users/agil/.kit/main/index.js 
[17:29:00.253] [info] 🏃‍♀️ Run /Users/agil/.kit/main/index.js
[17:29:00.251] [info] 🏚  main shortcut
[17:28:23.589] [info] 38619: 🛑 removed
[17:28:23.588] [info] 38619: 🟡 exit 0. Prompt process: /Users/agil/.kit/help/tail-log.js
[17:28:23.588] [info] EXIT { pid: 38619, code: 0 }
[17:28:23.578] [info] DISCONNECT
[17:28:21.439] [info] 39726: 🟢 start idle Prompt
[17:28:21.438] [info] 👶 Create child Prompt process  []
[17:28:21.355] [info] 📄 scriptPath changed: /Users/agil/.kit/help/tail-log.js
[17:28:21.336] [info] Another script is already controlling the UI. Denying UI control: tail-log.js
[17:28:21.335] [info] 38619: 🏎 /Users/agil/.kit/help/tail-log.js 
[17:28:21.335] [info] 🏃‍♀️ Run /Users/agil/.kit/help/tail-log.js
[17:28:21.335] [info] Show App: /Users/agil/.kit/help/tail-log.js
[17:28:21.331] [info] 🎨 Tray icon: default
[17:27:40.713] [info] ↖ Bounds: Prompt none ui { x: 1120, y: 233, width: 768, height: 480 }
[17:27:40.706] [info] 38618: 🛑 removed
[17:27:40.705] [info] 38618: 🟡 exit 0. Prompt process: /Users/agil/.kit/main/index.js
[17:27:40.705] [info] EXIT { pid: 38618, code: 0 }
[17:27:40.704] [info] DISCONNECT
[17:27:40.598] [info] 🎨 Tray icon: default
[17:27:34.242] [info] >>>> COPY
[17:27:25.703] [info] Prompt window in bounds.
[17:27:24.703] [info] ↖ Bounds: Prompt arg ui { x: 1120, y: 233, width: 768, height: 480 }
[17:27:24.694] [info] 38618: Prompt #5 complete 👍
[17:27:23.764] [info] ↖ Bounds: Prompt arg ui { x: 1120, y: 233, width: 768, height: 480 }
[17:27:23.759] [info] 38618: Prompt #4 complete 👍
[17:27:23.751] [info] ↖ Bounds: Prompt arg ui { x: 1120, y: 233, width: 768, height: 480 }
[17:27:23.748] [info] 38618: Prompt #4 complete 👍
[17:27:23.739] [info] Hours since sync: 0
[17:26:41.571] [info] Prompt window in bounds.
[17:26:40.567] [info] ↖ Bounds: Prompt arg ui { x: 1120, y: 233, width: 768, height: 480 }
    at process.processTicksAndRejections (node:internal/process/task_queues:96:5)
    at file:///Users/agil/.kit/main/kit.js:9:7
    at run (file:///Users/agil/.kit/core/utils.js:407:26)
    at resolveToScriptPath (file:///Users/agil/.kit/core/utils.js:164:11)
[17:26:40.558] [warn] Error: /Users/agil/.kit/cli/cli/switch-to-ts.js not found
[17:26:40.558] [warn] ☠️ ERROR PROMPT SHOULD SHOW ☠️
[17:26:40.558] [info] 38618: Prompt #2 complete 👍
[17:26:40.557] [info] 38618: Value submitted ✅ 
[17:26:13.742] [info] Prompt window in bounds.
[17:26:12.742] [info] ↖ Bounds: Prompt arg ui { x: 1120, y: 233, width: 768, height: 480 }
```

**Comment by johnlindquist** [comment]
Oh, sorry, a newer guide was pushed out with changed paths for the build which I'm shipping later tonight.

You can manually switch to TS by updating your:
`~/.kenv/.env` file and adding this line anywhere:

```bash
KIT_MODE=ts
```
