### ISSUE TITLE
Windows 10 Install failure

### ISSUE THREAD

**Issue by Froskk** [johnlindquist/kit#993]
```
Error: spawn C:\Users\rossc\AppData\Local\Programs\kit\resources\fallbacks\windows\clipboard_x86_64.exe ENOENT
    at r (C:\Users\rossc\AppData\Local\Programs\kit\resources\app.asar\main.prod.js:2:543688)
    at n (C:\Users\rossc\AppData\Local\Programs\kit\resources\app.asar\main.prod.js:2:543859)
    at ChildProcess.e.emit (C:\Users\rossc\AppData\Local\Programs\kit\resources\app.asar\main.prod.js:2:544000)
    at Process.ChildProcess._handle.onexit (node:internal/child_process:291:12)
```

---

Kit 1.40.62
Electron 22.0.0
win32 10.0.19044
Locale: en-GB

**Comment by johnlindquist** [comment]
@Froskk Can you please try this fix and see if it works for you?

https://github.com/johnlindquist/kit/issues/984#issuecomment-1379993381

**Comment by thunfisch987** [comment]
had the same error and that fixed it 👍

**Comment by Froskk** [comment]
#984 did indeed fix my issues. Cheers
