### ISSUE TITLE
Trouble installing on Windows

### ISSUE THREAD

**Issue by eddiemcconkie** [johnlindquist/kit#997]
```
Error: write EOF
    at WriteWrap.onWriteComplete [as oncomplete] (node:internal/stream_base_commons:94:16)
```

---

Kit 1.40.62
Electron 22.0.0
win32 10.0.22621
Locale: en-US

**Comment by johnlindquist** [comment]
@eddiemcconkie 

Main.log: %USERPROFILE%\AppData\Roaming\Kit\logs\main.log
Kit.log: %USERPROFILE%.kit\logs\kit.log

Or let me know if anything looks suspicious. I've installed the Windows version on 3 machines at home without issue, so I need to rely on the community to help me track these down.

**Comment by eddiemcconkie** [comment]
```
🟢🟢 🟢  !!!SCRIPT KIT TIME!!! 🟢 🟢 🟢 
[2023-01-18 11:54:46.298] [info] 
Release channel: main
Arch: x64
Platform: win32
Node version: v16.17.1
Node path: C:\Users\edwar\.knode\bin\node.exe
Electron version: 22.0.0
Electron Node version: 16.17.1
Electron Chromium version: 108.0.5359.62
Electron execPath: C:\Users\edwar\AppData\Local\Programs\kit\Kit.exe

[2023-01-18 11:54:46.360] [info] 🎨 Creating tray... { checkDb: true }
[2023-01-18 11:54:46.362] [info] 🎨 Tray icon: busy
[2023-01-18 11:54:46.390] [info] Tray created
[2023-01-18 11:54:46.391] [info] 🧐 Checking C:\Users\edwar\.kit {
  cwd: 'C:\\Users\\edwar\\.kit',
  encoding: 'utf-8',
  env: {
    KIT: 'C:\\Users\\edwar\\.kit',
    KENV: 'C:\\Users\\edwar\\.kenv',
    PATH: 'C:\\Users\\edwar\\.knode\\bin;C:\\Users\\edwar\\.kit\\bin;C:\\Users\\edwar\\.kenv\\bin;C:\\Python310\\Scripts\\;C:\\Python310\\;C:\\Program Files\\Oculus\\Support\\oculus-runtime;C:\\Python39\\Scripts\\;C:\\Python39\\;C:\\windows\\system32;C:\\windows;C:\\windows\\System32\\Wbem;C:\\windows\\System32\\WindowsPowerShell\\v1.0\\;C:\\windows\\System32\\OpenSSH\\;C:\\Program Files (x86)\\NVIDIA Corporation\\PhysX\\Common;C:\\Program Files\\NVIDIA Corporation\\NVIDIA NvDLISR;C:\\Program Files\\dotnet\\;C:\\Program Files (x86)\\dotnet\\;C:\\Program Files\\Microsoft VS Code\\bin;C:\\ProgramData\\chocolatey\\bin;C:\\Program Files\\Git\\cmd;C:\\WINDOWS\\system32;C:\\WINDOWS;C:\\WINDOWS\\System32\\Wbem;C:\\WINDOWS\\System32\\WindowsPowerShell\\v1.0\\;C:\\WINDOWS\\System32\\OpenSSH\\;C:\\Program Files\\nodejs\\;C:\\Program Files (x86)\\PowerShell\\7\\;%SystemRoot%\\system32;%SystemRoot%;%SystemRoot%\\System32\\Wbem;%SYSTEMROOT%\\System32\\WindowsPowerShell\\v1.0\\;%SYSTEMROOT%\\System32\\OpenSSH\\;C:\\Users\\edwar\\AppData\\Local\\pnpm;C:\\Users\\edwar\\.cargo\\bin;C:\\Users\\edwar\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python39\\Scripts;C:\\Users\\edwar\\AppData\\Local\\Microsoft\\WindowsApps;C:\\Users\\edwar\\AppData\\Local\\GitHubDesktop\\bin;C:\\MinGW\\bin\\gcc;C:\\MinGW\\bin;C:\\Users\\edwar\\.dotnet\\tools;C:\\Selenium\\chromedriver_win32;C:\\sqlite\\sqlite-tools-win32-x86-3340100;C:\\Users\\edwar\\AppData\\Local\\gitkraken\\bin;C:\\laragon\\bin\\ngrok;C:\\Users\\edwar\\AppData\\Roaming\\npm;C:\\Program Files\\heroku\\bin;C:\\Program Files\\MongoDB\\Server\\5.0\\bin;C:\\Users\\edwar\\SurrealDB;C:\\Users\\edwar\\.deno\\bin;%USERPROFILE%\\AppData\\Local\\Microsoft\\WindowsApps;C:\\Windows\\System32;C:\\Windows;C:\\Python310\\Scripts\\;C:\\Python310\\;C:\\Program Files\\Oculus\\Support\\oculus-runtime;C:\\Python39\\Scripts\\;C:\\Python39\\;C:\\windows\\system32;C:\\windows;C:\\windows\\System32\\Wbem;C:\\windows\\System32\\WindowsPowerShell\\v1.0\\;C:\\windows\\System32\\OpenSSH\\;C:\\Program Files (x86)\\NVIDIA Corporation\\PhysX\\Common;C:\\Program Files\\NVIDIA Corporation\\NVIDIA NvDLISR;C:\\Program Files\\dotnet\\;C:\\Program Files (x86)\\dotnet\\;C:\\Program Files\\Microsoft VS Code\\bin;C:\\ProgramData\\chocolatey\\bin;C:\\Program Files\\Git\\cmd;C:\\WINDOWS\\system32;C:\\WINDOWS;C:\\WINDOWS\\System32\\Wbem;C:\\WINDOWS\\System32\\WindowsPowerShell\\v1.0\\;C:\\WINDOWS\\System32\\OpenSSH\\;C:\\Program Files\\nodejs\\;C:\\Program Files (x86)\\PowerShell\\7\\;%SystemRoot%\\system32;%SystemRoot%;%SystemRoot%\\System32\\Wbem;%SYSTEMROOT%\\System32\\WindowsPowerShell\\v1.0\\;%SYSTEMROOT%\\System32\\OpenSSH\\;C:\\Users\\edwar\\AppData\\Local\\pnpm;C:\\Users\\edwar\\.cargo\\bin;C:\\Users\\edwar\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python39\\Scripts;C:\\Users\\edwar\\AppData\\Local\\Microsoft\\WindowsApps;C:\\Users\\edwar\\AppData\\Local\\GitHubDesktop\\bin;C:\\MinGW\\bin\\gcc;C:\\MinGW\\bin;C:\\Users\\edwar\\.dotnet\\tools;C:\\Selenium\\chromedriver_win32;C:\\sqlite\\sqlite-tools-win32-x86-3340100;C:\\Users\\edwar\\AppData\\Local\\gitkraken\\bin;C:\\laragon\\bin\\ngrok;C:\\Users\\edwar\\AppData\\Roaming\\npm;C:\\Program Files\\heroku\\bin;C:\\Program Files\\MongoDB\\Server\\5.0\\bin;;C:\\Users\\edwar\\SurrealDB;C:\\Users\\edwar\\.deno\\bin;%USERPROFILE%\\AppData\\Local\\Microsoft\\WindowsApps;C:\\Users\\edwar\\SurrealDB'
  },
  stdio: 'pipe'
}
[2023-01-18 11:54:47.572] [info] Prompt window created
[2023-01-18 11:54:47.572] [info] 

---------------------------------
[2023-01-18 11:54:47.573] [info] Launching Script Kit  1.40.62
[2023-01-18 11:54:47.574] [info] auto updater detected version: 1.40.62
[2023-01-18 11:54:47.574] [info] PATH: C:\Users\edwar\.knode\bin;C:\Users\edwar\.kit\bin;C:\Users\edwar\.kenv\bin;C:\Python310\Scripts\;C:\Python310\;C:\Program Files\Oculus\Support\oculus-runtime;C:\Python39\Scripts\;C:\Python39\;C:\windows\system32;C:\windows;C:\windows\System32\Wbem;C:\windows\System32\WindowsPowerShell\v1.0\;C:\windows\System32\OpenSSH\;C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common;C:\Program Files\NVIDIA Corporation\NVIDIA NvDLISR;C:\Program Files\dotnet\;C:\Program Files (x86)\dotnet\;C:\Program Files\Microsoft VS Code\bin;C:\ProgramData\chocolatey\bin;C:\Program Files\Git\cmd;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\WINDOWS\System32\OpenSSH\;C:\Program Files\nodejs\;C:\Program Files (x86)\PowerShell\7\;%SystemRoot%\system32;%SystemRoot%;%SystemRoot%\System32\Wbem;%SYSTEMROOT%\System32\WindowsPowerShell\v1.0\;%SYSTEMROOT%\System32\OpenSSH\;C:\Users\edwar\AppData\Local\pnpm;C:\Users\edwar\.cargo\bin;C:\Users\edwar\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\Scripts;C:\Users\edwar\AppData\Local\Microsoft\WindowsApps;C:\Users\edwar\AppData\Local\GitHubDesktop\bin;C:\MinGW\bin\gcc;C:\MinGW\bin;C:\Users\edwar\.dotnet\tools;C:\Selenium\chromedriver_win32;C:\sqlite\sqlite-tools-win32-x86-3340100;C:\Users\edwar\AppData\Local\gitkraken\bin;C:\laragon\bin\ngrok;C:\Users\edwar\AppData\Roaming\npm;C:\Program Files\heroku\bin;C:\Program Files\MongoDB\Server\5.0\bin;C:\Users\edwar\SurrealDB;C:\Users\edwar\.deno\bin;%USERPROFILE%\AppData\Local\Microsoft\WindowsApps;C:\Windows\System32;C:\Windows
[2023-01-18 11:54:47.577] [info] Checking online status...
[2023-01-18 11:54:47.592] [info] 📁 GET_ASSET svg/logo.svg
[2023-01-18 11:54:47.593] [info] 📁 Asset path: C:/Users/edwar/AppData/Local/Programs/kit/resources/assets/svg/logo.svg
[2023-01-18 11:54:47.620] [info] 🗼 Status: Online
[2023-01-18 11:54:47.625] [info] Stored version: 0.0.0
[2023-01-18 11:54:47.626] [info] C:\Users\edwar\.kit
[2023-01-18 11:54:47.626] [info] kit found
[2023-01-18 11:54:47.636] [info] 📄 scriptPath changed: __app__/splash-screen
[2023-01-18 11:54:47.639] [info] 🌊 Showing Splash Install Screen
[2023-01-18 11:54:47.658] [info] WebContents Focus
[2023-01-18 11:54:47.697] [info] 🔥 Starting Kit First Install
[2023-01-18 11:54:47.699] [info] node not found
[2023-01-18 11:54:47.699] [info] node not found
[2023-01-18 11:54:47.700] [info] Adding node v16.17.1 win32 x64 ~\.knode
[2023-01-18 11:54:47.704] [info] 📁 GET_ASSET icon.png
[2023-01-18 11:54:47.705] [info] 📁 Asset path: C:/Users/edwar/AppData/Local/Programs/kit/resources/assets/icon.png
[2023-01-18 11:54:47.706] [info] Focus
[2023-01-18 11:54:47.708] [info] Download node.js from https://nodejs.org/dist/v16.17.1/node-v16.17.1-win-x64.zip
[2023-01-18 11:54:47.741] [info] ↖ Bounds: Prompt splash ui { x: 384, y: 102, width: 768, height: 480 }
[2023-01-18 11:54:48.203] [info] WebContents Focus
[2023-01-18 11:54:48.206] [info] Focus
[2023-01-18 11:54:48.710] [info] Prompt window in bounds.
[2023-01-18 11:54:51.683] [info] Node download complete. Beginning extraction...
[2023-01-18 11:54:51.684] [info] Removing old node ~\.knode
[2023-01-18 11:54:51.838] [info] Create node dir ~\.knode
[2023-01-18 11:54:51.839] [info] Found C:/Users/edwar/AppData/Local/Programs/kit/resources/assets/node.zip. Extracting...
[2023-01-18 11:54:51.840] [info] Extracting C:/Users/edwar/AppData/Local/Programs/kit/resources/assets/node.zip to ~\.knode
[2023-01-18 11:54:57.016] [error] Error: EPERM: operation not permitted, rename 'C:\Users\edwar\.knode\node-v16.17.1-win-x64' -> 'C:\Users\edwar\.knode\bin'
[2023-01-18 11:54:57.021] [info] Stored version: 0.0.0 -> Current version: 1.40.62
[2023-01-18 11:54:57.022] [info] Requires install: true
[2023-01-18 11:54:57.040] [info] C:\Users\edwar\.kit
[2023-01-18 11:54:57.041] [info] kit found
[2023-01-18 11:54:57.042] [info] Didn't find C:\Users\edwar\.kit\.kitignore
[2023-01-18 11:54:57.043] [info] C:\Users\edwar\.kit
[2023-01-18 11:54:57.044] [info] kit found
[2023-01-18 11:54:57.045] [info] Cleaning previous .kit
[2023-01-18 11:54:57.046] [info] 🧹 Cleaning C:\Users\edwar\.kit
[2023-01-18 11:54:57.057] [info] 🧹 Cleaning dir C:\Users\edwar\.kit\api
[2023-01-18 11:54:57.059] [info] 🧹 Cleaning file C:\Users\edwar\.kit\API.md
[2023-01-18 11:54:57.062] [info] 🧹 Cleaning dir C:\Users\edwar\.kit\bin
[2023-01-18 11:54:57.068] [info] 🧹 Cleaning dir C:\Users\edwar\.kit\build
[2023-01-18 11:54:57.071] [info] 🧹 Cleaning dir C:\Users\edwar\.kit\ci
[2023-01-18 11:54:57.111] [info] 🧹 Cleaning dir C:\Users\edwar\.kit\cli
[2023-01-18 11:54:57.113] [info] 🧹 Cleaning file C:\Users\edwar\.kit\CODE_OF_CONDUCT.md
[2023-01-18 11:54:57.120] [info] 🧹 Cleaning dir C:\Users\edwar\.kit\core
[2023-01-18 11:54:57.121] [info] 👍 Keeping db
[2023-01-18 11:54:57.124] [info] 🧹 Cleaning dir C:\Users\edwar\.kit\debug
[2023-01-18 11:54:57.129] [info] 🧹 Cleaning dir C:\Users\edwar\.kit\emoji
[2023-01-18 11:54:57.131] [info] 🧹 Cleaning file C:\Users\edwar\.kit\GUIDE.md
[2023-01-18 11:54:57.141] [info] 🧹 Cleaning dir C:\Users\edwar\.kit\handler
[2023-01-18 11:54:57.146] [info] 🧹 Cleaning dir C:\Users\edwar\.kit\help
[2023-01-18 11:54:57.153] [info] 🧹 Cleaning dir C:\Users\edwar\.kit\hot
[2023-01-18 11:54:57.158] [info] 🧹 Cleaning dir C:\Users\edwar\.kit\icons
[2023-01-18 11:54:57.161] [info] 🧹 Cleaning dir C:\Users\edwar\.kit\images
[2023-01-18 11:54:57.163] [info] 🧹 Cleaning file C:\Users\edwar\.kit\index.d.ts
[2023-01-18 11:54:57.165] [info] 🧹 Cleaning file C:\Users\edwar\.kit\index.js
[2023-01-18 11:54:57.168] [info] 🧹 Cleaning file C:\Users\edwar\.kit\index.js.map
[2023-01-18 11:54:57.171] [info] 🧹 Cleaning file C:\Users\edwar\.kit\kar
[2023-01-18 11:54:57.172] [info] 🧹 Cleaning file C:\Users\edwar\.kit\KIT.md
[2023-01-18 11:54:57.178] [info] 🧹 Cleaning dir C:\Users\edwar\.kit\lib
[2023-01-18 11:54:57.180] [info] 🧹 Cleaning file C:\Users\edwar\.kit\LICENSE
[2023-01-18 11:54:57.188] [info] 🧹 Cleaning dir C:\Users\edwar\.kit\logos
[2023-01-18 11:54:57.202] [info] 🧹 Cleaning dir C:\Users\edwar\.kit\main
[2023-01-18 11:54:57.208] [info] 🧹 Cleaning dir C:\Users\edwar\.kit\node
[2023-01-18 11:54:57.209] [info] 👍 Keeping node_modules
[2023-01-18 11:54:57.214] [info] 🧹 Cleaning dir C:\Users\edwar\.kit\override
[2023-01-18 11:54:57.216] [info] 🧹 Cleaning file C:\Users\edwar\.kit\package-lock.json
[2023-01-18 11:54:57.218] [info] 🧹 Cleaning file C:\Users\edwar\.kit\package.json
[2023-01-18 11:54:57.222] [info] 🧹 Cleaning dir C:\Users\edwar\.kit\permissions
[2023-01-18 11:54:57.226] [info] 🧹 Cleaning dir C:\Users\edwar\.kit\platform
[2023-01-18 11:54:57.236] [info] 🧹 Cleaning dir C:\Users\edwar\.kit\pro
[2023-01-18 11:54:57.238] [info] 🧹 Cleaning file C:\Users\edwar\.kit\README.md
[2023-01-18 11:54:57.243] [info] 🧹 Cleaning dir C:\Users\edwar\.kit\run
[2023-01-18 11:54:57.245] [info] 🧹 Cleaning file C:\Users\edwar\.kit\script
[2023-01-18 11:54:57.248] [info] 🧹 Cleaning dir C:\Users\edwar\.kit\scripts
[2023-01-18 11:54:57.255] [info] 🧹 Cleaning dir C:\Users\edwar\.kit\setup
[2023-01-18 11:54:57.258] [info] 🧹 Cleaning dir C:\Users\edwar\.kit\share
[2023-01-18 11:54:57.260] [info] 🧹 Cleaning file C:\Users\edwar\.kit\sk
[2023-01-18 11:54:57.264] [info] 🧹 Cleaning dir C:\Users\edwar\.kit\target
[2023-01-18 11:54:57.271] [info] 🧹 Cleaning dir C:\Users\edwar\.kit\templates
[2023-01-18 11:54:57.277] [info] 🧹 Cleaning dir C:\Users\edwar\.kit\tmp
[2023-01-18 11:54:57.281] [info] 🧹 Cleaning dir C:\Users\edwar\.kit\types
[2023-01-18 11:54:57.282] [info] .kit doesn't exist or isn't on a contributor branch
[2023-01-18 11:54:57.296] [info] Download SDK from https://github.com/johnlindquist/kitapp/releases/download/v1.40.62/Kit-SDK-Windows-1.40.62-x64.tar.gz
[2023-01-18 11:54:57.297] [info] Downloading pre-bundled kit...
[2023-01-18 11:55:00.130] [info] Downloading complete. Beginning extraction...
[2023-01-18 11:55:00.130] [info] Extracting kit.tar.gz to ~\.kit
[2023-01-18 11:55:26.693] [info] .kit installed
[2023-01-18 11:55:26.694] [info] PATH: C:\Users\edwar\.knode\bin;C:\Users\edwar\.kit\bin;C:\Users\edwar\.kenv\bin;C:\Python310\Scripts\;C:\Python310\;C:\Program Files\Oculus\Support\oculus-runtime;C:\Python39\Scripts\;C:\Python39\;C:\windows\system32;C:\windows;C:\windows\System32\Wbem;C:\windows\System32\WindowsPowerShell\v1.0\;C:\windows\System32\OpenSSH\;C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common;C:\Program Files\NVIDIA Corporation\NVIDIA NvDLISR;C:\Program Files\dotnet\;C:\Program Files (x86)\dotnet\;C:\Program Files\Microsoft VS Code\bin;C:\ProgramData\chocolatey\bin;C:\Program Files\Git\cmd;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\WINDOWS\System32\OpenSSH\;C:\Program Files\nodejs\;C:\Program Files (x86)\PowerShell\7\;%SystemRoot%\system32;%SystemRoot%;%SystemRoot%\System32\Wbem;%SYSTEMROOT%\System32\WindowsPowerShell\v1.0\;%SYSTEMROOT%\System32\OpenSSH\;C:\Users\edwar\AppData\Local\pnpm;C:\Users\edwar\.cargo\bin;C:\Users\edwar\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\Scripts;C:\Users\edwar\AppData\Local\Microsoft\WindowsApps;C:\Users\edwar\AppData\Local\GitHubDesktop\bin;C:\MinGW\bin\gcc;C:\MinGW\bin;C:\Users\edwar\.dotnet\tools;C:\Selenium\chromedriver_win32;C:\sqlite\sqlite-tools-win32-x86-3340100;C:\Users\edwar\AppData\Local\gitkraken\bin;C:\laragon\bin\ngrok;C:\Users\edwar\AppData\Roaming\npm;C:\Program Files\heroku\bin;C:\Program Files\MongoDB\Server\5.0\bin;C:\Users\edwar\SurrealDB;C:\Users\edwar\.deno\bin;%USERPROFILE%\AppData\Local\Microsoft\WindowsApps;C:\Windows\System32;C:\Windows;C:\Python310\Scripts\;C:\Python310\;C:\Program Files\Oculus\Support\oculus-runtime;C:\Python39\Scripts\;C:\Python39\;C:\windows\system32;C:\windows;C:\windows\System32\Wbem;C:\windows\System32\WindowsPowerShell\v1.0\;C:\windows\System32\OpenSSH\;C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common;C:\Program Files\NVIDIA Corporation\NVIDIA NvDLISR;C:\Program Files\dotnet\;C:\Program Files (x86)\dotnet\;C:\Program Files\Microsoft VS Code\bin;C:\ProgramData\chocolatey\bin;C:\Program Files\Git\cmd;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\WINDOWS\System32\OpenSSH\;C:\Program Files\nodejs\;C:\Program Files (x86)\PowerShell\7\;%SystemRoot%\system32;%SystemRoot%;%SystemRoot%\System32\Wbem;%SYSTEMROOT%\System32\WindowsPowerShell\v1.0\;%SYSTEMROOT%\System32\OpenSSH\;C:\Users\edwar\AppData\Local\pnpm;C:\Users\edwar\.cargo\bin;C:\Users\edwar\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\Scripts;C:\Users\edwar\AppData\Local\Microsoft\WindowsApps;C:\Users\edwar\AppData\Local\GitHubDesktop\bin;C:\MinGW\bin\gcc;C:\MinGW\bin;C:\Users\edwar\.dotnet\tools;C:\Selenium\chromedriver_win32;C:\sqlite\sqlite-tools-win32-x86-3340100;C:\Users\edwar\AppData\Local\gitkraken\bin;C:\laragon\bin\ngrok;C:\Users\edwar\AppData\Roaming\npm;C:\Program Files\heroku\bin;C:\Program Files\MongoDB\Server\5.0\bin;;C:\Users\edwar\SurrealDB;C:\Users\edwar\.deno\bin;%USERPROFILE%\AppData\Local\Microsoft\WindowsApps;C:\Users\edwar\SurrealDB
[2023-01-18 11:55:26.857] [info] 🔨 Running Setup Script C:\Users\edwar\.kit\setup\chmod-helpers.js
[2023-01-18 11:55:30.691] [info] ✅ Successfully ran C:\Users\edwar\.kit\setup\chmod-helpers.js
[2023-01-18 11:55:30.693] [info] ⛑ Clear prompt cache: {}
[2023-01-18 11:55:30.698] [info] kenv found
[2023-01-18 11:55:30.699] [info] Running optional setup script: C:\Users\edwar\.kit\setup\build-ts-scripts.js
[2023-01-18 11:55:30.710] [info] kenv is configured
[2023-01-18 11:55:30.710] [info] Update .kenv
[2023-01-18 11:55:30.711] [info] 🔨 Running Setup Script C:\Users\edwar\.kit\setup\patch.js
[2023-01-18 11:55:31.534] [info] ✅ Successfully ran C:\Users\edwar\.kit\setup\patch.js
[2023-01-18 11:55:31.535] [info] Creating bins
[2023-01-18 11:55:31.535] [info] Running optional setup script: C:\Users\edwar\.kit\cli\create-all-bins-no-trash.js
[2023-01-18 11:55:31.550] [info] Verifying ~/.kit exists:
[2023-01-18 11:55:31.551] [info] C:\Users\edwar\.kit
[2023-01-18 11:55:31.552] [info] kit found
[2023-01-18 11:55:31.552] [info] Verifying ~/.kenv exists:
[2023-01-18 11:55:31.553] [info] kenv found
[2023-01-18 11:55:31.554] [info] node not found
[2023-01-18 11:55:31.554] [info] node missing
[2023-01-18 11:55:31.555] [info] node_modules found
[2023-01-18 11:55:31.556] [info] node_modules found
[2023-01-18 11:55:31.556] [info] kenv is configured
[2023-01-18 11:55:31.557] [info] kenv .env found
[2023-01-18 11:55:31.558] [warn] Install not verified...
[2023-01-18 11:55:31.582] [warn] Error: Install not verified...
    at C:\Users\edwar\AppData\Local\Programs\kit\resources\app.asar\main.prod.js:2:500511
    at l (C:\Users\edwar\AppData\Local\Programs\kit\resources\app.asar\main.prod.js:2:478683)
    at Generator.<anonymous> (C:\Users\edwar\AppData\Local\Programs\kit\resources\app.asar\main.prod.js:2:480021)
    at Generator.next (C:\Users\edwar\AppData\Local\Programs\kit\resources\app.asar\main.prod.js:2:479046)
    at vd (C:\Users\edwar\AppData\Local\Programs\kit\resources\app.asar\main.prod.js:2:484675)
    at a (C:\Users\edwar\AppData\Local\Programs\kit\resources\app.asar\main.prod.js:2:484879)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
[2023-01-18 11:55:31.584] [info] ✅ Successfully ran setup script: C:\Users\edwar\.kit\setup\build-ts-scripts.js
[2023-01-18 11:55:31.644] [error] Error: spawn C:\Users\edwar\AppData\Local\Programs\kit\resources\fallbacks\windows\clipboard_x86_64.exe ENOENT
    at r (C:\Users\edwar\AppData\Local\Programs\kit\resources\app.asar\main.prod.js:2:543688)
    at n (C:\Users\edwar\AppData\Local\Programs\kit\resources\app.asar\main.prod.js:2:543859)
    at ChildProcess.e.emit (C:\Users\edwar\AppData\Local\Programs\kit\resources\app.asar\main.prod.js:2:544000)
    at Process.ChildProcess._handle.onexit (node:internal/child_process:291:12)
[2023-01-18 11:55:54.618] [info] WebContents Focus
[2023-01-18 11:55:54.632] [info] Focus
[2023-01-18 11:55:54.633] [info] ✅ Successfully ran setup script: C:\Users\edwar\.kit\cli\create-all-bins-no-trash.js
```

**Comment by johnlindquist** [comment]
Can you try this fix?

https://github.com/johnlindquist/kit/issues/984#issuecomment-1379993381

The line:

`[2023-01-18 11:55:31.554] [info] node missing`

is saying that something went wrong setting up node at `%USERPROFILE%\.knode`.

**Comment by eddiemcconkie** [comment]
@johnlindquist Yes that worked!! Thanks, I'm really excited to try this out!
